### ISSUE TITLE
WIFI card Intel Advanced-N 6200 AGN not detected

### ISSUE THREAD

**Issue by z3huti** [puppylinux-woof-CE/woof-CE#2060] opened 2021-02-27 11:27 UTC
BionicPup64 8.0 does not detect WIFI card Intel Advanced-N 6200 AGN

but BionicPup 32bit does

also Slacko Puppy 7.0 64bit does not detect it, but 32bit works

**Comment by dimkr** [comment] 2021-02-27 12:51
Hi @z3huti, can you share the output of `cat /proc/version` and `dmesg` from at least one scenario where it works and another where it doesn't?

**Comment by z3huti** [comment] 2021-02-27 13:26
> Hi @z3huti, can you share the output of `cat /proc/version` and `dmesg` from at least one scenario where it works and another where it doesn't?

https://drive.google.com/file/d/1q0D2HGWJIcn-jAb86ubnRD4oBUIBoxag/view?usp=sharing

**Comment by dimkr** [comment] 2021-02-27 13:31
The difference is here:

```
iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-6.ucode failed with error -2^M
iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-5.ucode failed with error -2^M
iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-4.ucode failed with error -2^M
iwlwifi 0000:03:00.0: no suitable firmware found!^M
iwlwifi 0000:03:00.0: minimum version required: iwlwifi-6000-4^M
iwlwifi 0000:03:00.0: maximum version supported: iwlwifi-6000-6^M
```

```
iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-6.ucode failed with error -2^M
iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-5.ucode failed with error -2^M
iwlwifi 0000:03:00.0: loaded firmware version 9.221.4.1 build 25532 op_mode iwldvm^M
iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEBUG disabled^M
iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEBUGFS disabled^M
iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEVICE_TRACING disabled^M
iwlwifi 0000:03:00.0: Detected Intel(R) Centrino(R) Advanced-N 6200 AGN, REV=0x74^M
```

Take `fdrv-*.sfs` from the Puppy where WiFi works and try to load it in the Puppy where it doesn't. If it doesn't have `fdrv-*.sfs`, try to copy the /lib/firmware directory, or just /lib/firmware/iwlwifi-6000-4.ucode, /lib/firmware/iwlwifi-6000-5.ucode or /lib/firmware/iwlwifi-6000-6.ucode.

**Comment by z3huti** [comment] 2021-02-27 13:41
I am just a user, reporting a "bug". Developers of puppy linux should fix it, and update ISOs.

**Comment by dimkr** [comment] 2021-02-27 13:48
> I am just a user, reporting a "bug".

Thanks for doing so.

> Developers of puppy linux should fix it, and update ISOs.

666philb doesn't provide updates of Bionicpup, so this problem won't get fixed and it's up to you to decide whether or not you want to fix it for yourself, or wait forever.

As far as I see, the problem is fixed for Slacko 8.0 - Intel firmware is packaged properly. @01micko Any idea what went wrong in 7.0?

**Comment by z3huti** [comment] 2021-02-27 14:08
> Any idea what went wrong in 7.0

Yes, an update on 2021-Jan-03. Before that it was ok.

**Comment by dimkr** [comment] 2021-02-27 14:12
Took a look in the 7.0 ISO and indeed, /lib/firmware/iwlwifi-6000-*.ucode is missing.

**Comment by mrfricks** [comment] 2021-02-27 17:39
hi @z3huti 
the missing firmware was added in a quickpet update for bionicpup64, so if you can plug a cable in to update and then reboot, wireless should work

**Comment by mrfricks** [comment] 2021-02-27 17:42
> Took a look in the 7.0 ISO and indeed, /lib/firmware/iwlwifi-6000-*.ucode is missing.

hi @dimkr i did mention this in the slacko thread somewhere :)

**Comment by dimkr** [comment] 2021-03-03 20:53
This bug is fixed in automated Slacko 7.x builds produced by #2067.

**Comment by dimkr** [comment] 2021-03-22 09:44
I'm closing this, it's a slacko 7.0 specific problem that's fixed in every future slacko.

**Comment by dimkr** [comment] 2021-03-22 09:44
@01micko How about publishing a 7.1 release, just to get this one fixed?

**Closed as completed by dimkr** 2021-03-22 09:44 UTC

**Comment by 01micko** [comment] 2021-03-22 09:47
Soon
