### ISSUE TITLE
quotation sign  warning

### ISSUE THREAD

**Issue by don570** [puppylinux-woof-CE/woof-CE#3360] opened 2022-08-31 23:28 UTC
When  the  search path  has a quotation  sign  (")
pfind doesn't work.

I suggest a warning.
After line  86  in func  file of pfilesearch

` #  Warn about  quotation  sign

		if  echo  "$SEARCHPATH" |  grep -q  '"' ; then 

		Xdialog --title "Warning"   --wrap    --ok-label "Close" --msgbox "Sorry.  Quotation sign detected in  search path"   0 0 &

		exit

		fi`

**Comment by Phoenix-Starlight** [comment] 2022-09-23 01:42
You can fork it, make changes and make a pull request. (Also can say 'Fixes #N' to mention this issue and link it)

**Comment by dimkr** [comment] 2022-09-23 06:41
Who maintains pfilesearch? @zigbert maybe?

**Comment by zigbert** [comment] 2022-09-23 20:48
It would logical be me... I just need time to take a dive into it. Haven't looked at the code for years... Won't be this week.

If I understand things right, we can close this issue. It is solved by issue #3381 pfilesearch fix written

@don570 , can you close this if not needed anymore

**Comment by dimkr** [comment] 2022-09-24 05:06
> we can close this issue

But the fix is not merged. Normally, a closed issue means "the issue is fixed", not "the fix is available somewhere".

**Comment by zigbert** [comment] 2022-09-24 19:27
I like coding - not the managing of github issues.

**Comment by zigbert** [comment] 2022-09-25 05:55
fixed in
https://github.com/puppylinux-woof-CE/woof-CE/commit/53fbc0bf40f7e8a7b1426117234a86913c4a41b6
https://github.com/puppylinux-woof-CE/woof-CE/commit/16a4aef457c939de3849fb4141232563040e035b

**Closed by zigbert** 2022-09-25 05:55 UTC
