### ISSUE TITLE
Github releases workflow warning.

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3548] opened 2022-10-24 08:19 UTC
Running releases through github workflows is causing this warning in upload job:-
![screenshot](https://user-images.githubusercontent.com/103126231/197480258-3ee5629d-ef16-4785-97ed-887176878f48.png)
Seems like release github workflow is using a command that is deprecated.

**Comment by dimkr** [comment] 2022-10-24 08:27
Duplicate of https://github.com/softprops/action-gh-release/issues/268.

**Comment by lakshayrohila** [comment] 2022-10-26 06:22
This issue would be resolved when softprops/action-gh-release will update to using environment files. Closing the issue as duplicate.

**Closed as not planned** 2022-10-26 06:23 UTC
