### ISSUE TITLE
graphical glitch

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#844] opened 2016-08-12 14:21 UTC
when puppy loads we get a green 'done' after each section of loading.
one of these dones is hanging around and reappears at the top of the screen momentarily  when X starts... 
even sometimes appearing after the desktop has appeared.

i initially thought it was a bug in xenial but i've just done a tahrpup64 build and it's there as well.
![dodgy_done](https://cloud.githubusercontent.com/assets/1454550/17625334/fd093bf4-60da-11e6-9961-7ff901c76553.jpg)

**Comment by wdlkmpx** [comment] 2016-08-12 17:09
unable to reproduce, send me a pm with a link to the iso

**Comment by wdlkmpx** [comment] 2016-08-12 17:16
or better yet, post it here and make sure to delete it in about 2 days.

**Comment by ninaholic** [comment] 2016-08-12 17:39
Hi mrfricks! I had the same issue with "testing" branch, in both slacko and devuan. It seems to be fixed in the "rationalise" branch though. :)

**Comment by wdlkmpx** [comment] 2016-08-12 20:04
thou shalt update

apparently commit https://github.com/puppylinux-woof-CE/woof-CE/commit/587f35d62d8bbae3f05be5779452c687125e4048 (7 aug) fixed several issues

and it seems that in fact there is an extra done message, but (at least on my pc) it goes unnoticed because things happen so fast..

 commit https://github.com/puppylinux-woof-CE/woof-CE/commit/ee35e3c73aa7726f05f4c3e75b43202a7e650cbc should remove that extra done message, but i'm not sure.. have to reboot.

**Comment by mrfricks** [comment] 2016-08-13 23:30
ninaholic  thanks for the info, i'll give a try.

wdlkmpx the 'done' still there for me..... i've uploaded a new iso built with the latest testing . http://distro.ibiblio.org/puppylinux/test/xenialpup/xenial-7.0.3.iso

**Comment by wdlkmpx** [comment] 2016-08-14 05:04
yes i can see it. it only appaers when i restart x. i'll try to figure out why...

**Comment by wdlkmpx** [comment] 2016-08-14 19:51
well, for xenial, you might want to use DOTconfig-4.4.17-i686-pae

i enabled random modules that looked interesting. the generated modules will be about 17-24MB xz compressed according to my projections. i remember enabling UEFI support following the Arch LInux wiki months ago..

so as a test build that will actually work in most cases so you don't to figure out what enable... this is ok.

**Comment by mrfricks** [comment] 2016-08-23 11:37
hi wdlkmpx,

there were problems for me with your new DOTconfig.  when booting at 'searching for puppy files' i get ..pausing...pausing...pausing ...  and X doesn't start.

the kernel/firmware combination is all that's holding xenial up..it was pretty much ready over 2months ago.
to be honest the 4* kernels have been a real headache! they'll work on one machine, not work on another and freeze on yet another. 4.4 and 4.6 freeze on my desktop , 4.4 freezes on my netbook, so i'm giving 4.7 a try and if that's problematic i'll stick with 4.1 as that has been the least problematic.

BTW i see that gyrog has fixed the errant 'done' in rationalise... can it be merged into testing?

**Comment by wdlkmpx** [comment] 2016-08-23 12:39
post a link to your latest iso here or send me a pm (and delete the
file in about 2 days), i'd like to test it..

**Comment by wdlkmpx** [comment] 2016-08-23 14:14
From what i read on the forum.. I get it now

Well, you should release a new tahrpup version, 7.0 with kernel 3.14.x .. that's what they want.

**Comment by ninaholic** [comment] 2016-08-26 20:38
I try 3.14.77 kernel building with new DOTconfig. It is booting ok this time. File sizes are:

3.14.77 with new build.sh / DOTconfig:
- 4841072 vmlinuz
- 33161216 zdrv.sfs

3.14.75 with old build.sh / DOTconfig:
- 4692192  vmlinuz
- 30064672 zdrv.sfs

So  about 3MB larger as wdlxmpx mentioned they might be. :partly_sunny:

**Comment by wdlkmpx** [comment] 2016-08-27 01:31
I haven't compile a 3.14 kernel in a while, but i think i enabled more
stuff since then. It appears the config for kernel 4.4 is buggy or
something according to what mrfrcisk previously said in this issue.. i
haven't compiled myself. But xenial is indeed a challenge with newer
kernels, according to him anyway, maybe systemd is finally
interfering?

**Comment by wdlkmpx** [comment] 2016-08-27 01:45
Although producing a fairly small kernels+firmware without people
complaining is not possible anymore, but a few firmware megabytes can
be removed if we look with clinical eyes in a per kernel basis..

**Comment by wdlkmpx** [comment] 2016-12-03 15:00
I used the xenial x86 configs for debian stretch, i deleted about 350 entries (and edited all the rest).. and plan to delete some more.

But i think i identified some issues, these entries should be deleted:

yes|xf86-video-nv||exe,dev,doc,nls| #ubuntu no longer has this.
yes|xf86-input-keyboard||exe,dev,doc,nls| #ubuntu no longer has this.
yes|xf86-input-mouse||exe,dev,doc,nls| #ubuntu no longer has this.

in xserver_xorg, this makes more sense:
xserver-xorg-input-*

Do you want me to fix it for you?

there are also random packages that just seem odd: 'momanager', etc. other packages that are up to date in noarch, but hardcoded for tahr, etc. etc. etc.

**Comment by mavrothal** [comment] 2017-03-14 06:05
reopen as needed

**Closed by mavrothal** 2017-03-14 06:05 UTC
