### ISSUE TITLE
sfwbar launcher exclusive zone is not 0

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#4024] opened 2023-04-24 08:14 UTC
Maximized applications cannot fill the space occupied by the launcher:

![image](https://user-images.githubusercontent.com/1471149/233937409-57a5b971-599c-4e29-845f-ea38a7241ac9.png)

Can be solved using:

![image](https://user-images.githubusercontent.com/1471149/233937911-a9f73726-fe68-4753-a996-802bb457c95a.png)

**Comment by 01micko** [comment] 2023-04-24 10:51
Never needed that in older versions; new 'feature'

**Comment by LBCrion** [comment] 2023-04-24 20:16
This shouldn't be new. Bars were always created with exclusive zone set to auto. Did the bar behave differently in the previous sfwbar versions?

**Comment by 01micko** [comment] 2023-04-24 21:42
Only the launcher in my config. Here is what I had in the init section.

```
function("SfwbarInit") {
  SetLayer "panel", "bottom"
  SetMonitor "panel", "DVI-D-1"
  SetExclusiveZone "panel", "40"
  SetLayer "launcher", "bottom"
  SetMonitor "launcher", "DVI-D-1"
  SetBarSize "launcher", "160"
}
```

But I'm happy to add @dimkr's suggestion.

EDIT: actually, I'm running an older labwc so the issue is likely there and fixed in later versions.

**Comment by dimkr** [comment] 2023-04-25 05:49
@01micko If you want all the labwc goodies on top of a stable base (= not Debian Sid), a Puppy that's both a daily driver and a development platform, I can backport labwc support to the Debian Bookworm based dpup 10.0.x series as an additional flavor. My daily driver is a dwl spin of dpup (https://github.com/dimkr/darls) and it works great.

**Comment by 01micko** [comment] 2023-04-25 06:09
No it's ok. I'll eventually get my slackware-current branch up and running and in the mean time I'm quite happy to run vanilla-dpup-11x. I can work around any bugs if I need to use as a daily anyway.

**Closed as completed** 2023-04-25 10:07 UTC
