### ISSUE TITLE
some jwmconfig/ptheme issues

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#631] opened 2015-11-07 13:20 UTC
- Left mouse click brings up the "activate mouse action" banner when clicking in an empty area on the desktop. Besides annoying and with no way to eliminate it, it interferes with the next left click as it used to close the banner and not the function intended (ie close a window, open an app etc).
- Since we are going with the minimal desktop icons by default, the top tray should  have autohide=off as a default, so a first time user can see what is available instead of going through the long menus.
- "Connect" should be included in the top tray as more puppians use it in laptops with wifi.
- Top tray has pMusic. Should be default audio/video player

**Comment by mavrothal** [comment] 2015-11-08 16:16
See also [here] (http://www.murga-linux.com/puppy/viewtopic.php?p=871482#871482) for an error due to the unknown original position of the top tray

BTW the 'left mouse click brings up the "activate mouse action" banner' above goes away if you select "blank" from the mouse action menu and restart X. However "blank" should be the default for left click

**Comment by zigbert** [comment] 2015-11-08 18:27
- Left mouse brings up "activate mouse actions":
This is as intended, and I think still this is how it should work.
It is nice to show new feature, and it is not in the users way if not having an unintentionally-clicking-habbit. If so, it can easily be deactivated.
- Toptray to be autohided:
Disagree. Let the desktop be clean. Our mission is to help the user fill the desktop - not actually fill it.
- Include connect icon:
Hmmm - what a minor issue :-) The setup icon is there...
- Change pmusic icon:
I don't know - maybe skip it instead. Mime settings should handle multimedia files....

**Comment by 01micko** [comment] 2015-11-08 20:03
> - Change pmusic icon: I don't know - maybe skip it instead. Mime settings should handle multimedia files....

Yes skip pburn and defaultmediaplayer too and maybe add the 'i' icon for help?

**Comment by zigbert** [comment] 2015-11-08 20:40
The 'problem' with the info-button, is that it does not has a *.desktop file - so jwm_config/tray is not capable to set this. - It has to be edited manually, which is not a problem at all - just a matter of principles. 

defaulthtmlviewer file:///usr/share/doc/index.html

**Comment by 01micko** [comment] 2015-11-08 21:17
Hmm I see. Hard coding doesn't allow Icon theme change. 

I forget the layout off hand, but does it have defaultpaint?

**Comment by mavrothal** [comment] 2015-11-08 21:37
> Left mouse brings up "activate mouse actions": This is as intended, and I think still this is how it should work. It is nice to show new feature, and it is not in the users way if not having an unintentionally-clicking-habbit.

I obviously disagree in every way. But all I'll say at this point is that is the first time I see an OS that left click actually does something  when clicking on an empty space. Unless we want to advertise Puppy as the "pedagogical OS" :-P  

>Toptray to be autohided: Disagree. Let the desktop be clean. Our mission is to help the user fill the desktop - not actually fill it.

I thought our mission was to show what the OS can do easily OOTB. 
Regarding "cleanness"  funny how the UI gold standard, Apple, things otherwise about its panel. 
And again, I'm trying to think of an OS that had by default a hidden desktop element and I can not. 
It is possible that they are all wrong but there is also a risk that we are reinventing the flat tire.

Anyway, I'm not going to lose any sleep over it. Do as you see fit.

**Comment by zigbert** [comment] 2015-11-08 21:55
Yes, it is possible to make a 'predefined function' button for 'Help' (as ie. the theme-buttons).... done

I'll look at the tray-template later:
- remove pmusic
- mtpaint to defaultpaint (if available)
- info button

Good night

**Comment by mavrothal** [comment] 2015-11-09 09:53
Another little thing. The way to delete a tray is not very evident (you need to clear the list).
Maybe the wording of the tooltip and the following box_yesno should be revised to indicate this ability  and the button move to a more "distinct" position

**Comment by zigbert** [comment] 2015-11-09 17:24
I suggest we just improve the tooltip and msg at this point. There are bigger things to be done after the merge.
- could it be possible to list human readable items in list instead of the actual rc file
- move help page so that first screen shows tray options
- fully support the absolute positioning (x/y). This might work as static screenlets as well... And if we succeed, the tray app needs further simplifying (because this adds more features, and the gui is already complex.)

**Comment by mavrothal** [comment] 2015-11-09 18:07
> I suggest we just improve the tooltip and msg at this point. 

OK. Let's do that then. 
I'm just not sure if it should it be "scary" or "informative"  :-?

**Comment by zigbert** [comment] 2015-11-09 22:15
A crazy idea - and maybe a bad one:
By autohiding the toptray, it can be on the top layer (above). Not autohiding the tray, it 'has' to be on a layer below the running apps. Else it takes too much space from the running apps. What I like the most by the toptray is that it is always available - above the apps. Ok, now to the idea: What if we mirror the toptray, and offers another equal tray not hidden, but below the apps. This concept would work in any case... - Visible and available. The major problem is that the user edits one of the trays, and does not realize that there is 2 trays. Maybe this can be a special feature in the next generation of the tray app.

**Comment by zigbert** [comment] 2015-11-09 22:27
mavrothal
Sorry!
I read your (and my) posts another time, and realize that you was referring to LEFT-mouse click. Somehow, I thought RIGHT-click. It should be no mouse-action for left-click. Now fixed!

Sorry!
Sigmund

**Comment by mavrothal** [comment] 2015-11-10 03:34
> Somehow, I thought RIGHT-click

 Somehow that's my case half of the times :smile: 

Regarding top tray. What about when always visible (not autohidden) is under and when autohidden is over. Best of both words in 1 tray.

Also would be nice when  the "Puppy standard" icon layout is selected in the pTheme or the Desktop Icon applets and there is a top tray, to default to autohidden.
(Jumping on a different issue, this is a problem with the Buntoo pTheme)

**Comment by 01micko** [comment] 2015-11-10 04:22
Buntoo is defaulting to zabuton icons now, i have them in slacko (upcoming in a few hours - deltas only)

**Comment by mavrothal** [comment] 2015-11-10 07:04
> upcoming in a few hours - deltas only

is this the slacko64-6.1.0.1.iso___slacko64_6.1.0.1.new.iso.delta ?
the slacko-6.1.0.1.iso___slacko-6.1.3.1.iso.delta?
Other?

**Comment by 01micko** [comment] 2015-11-10 07:28
I just uploaded slacko-6.1.0.1.iso___slacko-6.1.3.1.iso.delta

The other is just a kernel upgrade, manually done, well scripted so it had the ID string.

**Comment by mavrothal** [comment] 2015-11-10 07:32
6.1.3.1 is missing /root/.jwm/root-menus/menu1
so any theme change gets error
![menu1](https://cloud.githubusercontent.com/assets/1014999/11056773/d9e7f434-878d-11e5-9e4d-20e91a853e0f.png)

**Comment by 01micko** [comment] 2015-11-10 07:43
Oh well. I didn't change anything. All the other bugs (except 3g modems) are fixed!

**Comment by mavrothal** [comment] 2015-11-10 07:51
Yet is gone from the iso.
On the bright site, fixing this little bug allows for a smooth 6.1.3.1 update from 5.7!
The only issue there is that now when you change a theme with pTheme the puppy icon switcher applet comes up every time.
Maybe something that the "fix" script did.

**Comment by 01micko** [comment] 2015-11-10 07:56
Ah but wait... that was the one that caused the left click thingy so maybe changing in the git web UI killed the symlink? :confounded:

**Comment by 01micko** [comment] 2015-11-10 08:01
Yep, that's it for sure, I'll fix it in woof and build a new delta :-). Lucky i didn't announce!
If you add the symlink to menu_build_none it all works.

**Comment by 01micko** [comment] 2015-11-10 08:35
Works. New delta after dinner.  (hour or so)

**Comment by mavrothal** [comment] 2015-11-10 08:49
May have time for one more...
In the upgrade_ptheme_fix you need to make sure that then new version of icon_switcher is used, because the old one is one that is causing the appearance of the applet every time you change theme.
I guess ``` rm -f /initrd/pup_{rw,ro1}/usr/sbin/icon_switcher 2>/dev/null ``` somewhere should do.

**Comment by 01micko** [comment] 2015-11-10 09:08
ok.

**Closed** 2015-11-19 13:56 UTC
Labels: bug, enhancement

**Comment by 01micko** [comment] 2015-11-30 20:16
@zigbert - new theme for you to play with:  [feauxfwm](http://www.murga-linux.com/puppy/viewtopic.php?p=874994#874994)

**Comment by zigbert** [comment] 2015-11-30 22:50
Downloading :-)
What we need next is to control the drive icons in ptheme/global themes.

**Comment by zigbert** [comment] 2015-12-01 14:29
feauxfwm is really good looking. Especially the gtk/jwm colors. You impress me by your design work. The Puppy desktop will never be the same again. thumbs up :-).  I have some minor suggestions, but first I will finish the rewrite of the tray-script.
