### ISSUE TITLE
Boot params nox and xorgwizard do not work

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1086] opened 2017-09-18 09:35 UTC
pfix=nox
pfix=xorgwizard
do not work on any recent pups - e.g. slacko-6.9.9.9 BUILD_FROM_WOOF='testing;762210b;2017-06-13

**Comment by gyrog** [comment] 2017-09-18 11:27
"pfix=nox" should work, it does in slacko6.9.6.7
There has never been a "pfix=xorgwizard"

**Comment by gyrog** [comment] 2017-09-18 11:40
My mistake, looks like I'm behind the times.
There is now a "pfix=xorgwizard"

Support for both seems to still be present in "init".

**Comment by mavrothal** [comment] 2017-09-18 13:21
Looks like that /pup_new/tmp is not writable. Or busybox touch has some issue.
/initrd/tmp/bootinit.log shows (in Slacko64b- 6.9.9.9.)
```
touch: /pup_new/tmp/xwin_xorgwizard_cli: No such file or directory 
touch: /pup_new/tmp/bootcnt.txt: No such file or directory
```
So the flags are not passed after switching and indeed can not be found in /tmp

**Comment by peabee** [comment] 2017-09-18 15:45
I have been able to reinstate the pfix=nox process by putting the /sbin/init and /etc/profile from xenialpup-7.0.8.1 into a ydrv
The problem must have been introduced shortly before slacko-6.9.9.9 with BUILD_FROM_WOOF='testing;762210b;2017-06-13

**Comment by mavrothal** [comment] 2017-09-18 15:50
The problem is a typo at [line 1473 of the init](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/initrd-progs/0initrd/init#L1473),  should be  ```ln -sv /pup_new/initrd/mnt/tmpfs/tmp /pup_new/tmp``` (pup_new is missing).
The problem is that after that xorgwizard(-cli, -automatic) does not really run spitting  a bunch of errors!
Needs some more looking at...

**Comment by mavrothal** [comment] 2017-09-18 16:04
The above "solution" breaks /tmp after switching root (still points to  /pup_new/initrd/mnt/tmpfs/tmp), hence the issues with xorgwizard. 
However, the original problem, is the absence of the ```/initrd/mnt/tmpfs/tmp``` directory in the init that results in broken  ```/pup_new/tmp```
Needs a bit more careful looking at.

**Comment by mavrothal** [comment] 2017-09-18 19:24
This patch works for me in passing the flags. 
It saves them in inird /tmp and rc.sysinit moves them from /inird/tmp to /tmp.
Consider as needed
```
From 9694e2925d1c41359ccdde3f982502b02293fe41 Mon Sep 17
From: mavrothal <mavrothal@yahoo.com>
Date: Mon, 18 Sep 2017 22:17:09 +0300
Subject: [PATCH] pass bootflags to main os

---
 initrd-progs/0initrd/init                     | 5 +++--
 woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit | 4 ++++
 2 files changed, 7 insertions(+), 2 deletions(-)

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
index bb5da8a..6a4952c 100755
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -1484,9 +1484,10 @@ if [ "$COPY_CRYPTSETUP" = "yes" ] ; then
       cp -v /bin/cryptsetup /pup_new/sbin/
 fi
 
-[ "$PXORGWIZARD" = "yes" ] && touch /pup_new/tmp/xwin_xorgwizard_cli
+mkdir /tmp/initflags
+[ "$PXORGWIZARD" = "yes" ] && touch /tmp/initflags/xwin_xorgwizard_cli
 #PNOX is a boot param. /etc/profile prevents X from starting if this file exists...
-[ "$PNOX" = "yes" ] && touch /pup_new/tmp/bootcnt.txt
+[ "$PNOX" = "yes" ] && touch /tmp/initflags/bootcnt.txt
 cp -a /DISTRO_SPECS /pup_new/initrd/
 cp /init* /pup_new/initrd/
 chmod -x /pup_new/initrd/init
diff --git a/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit b/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
index c9f0a2c..4f3b74d 100755
--- a/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
+++ b/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
@@ -259,6 +259,10 @@ mount -t sysfs none /sys ;STATUS=$((STATUS+$?))
 mkdir -p /dev/shm #120503 if kernel mounts a f.s. on /dev, removes my skeleton /dev
 mount -t tmpfs -o size=${QTRFREERAM}k shmfs /dev/shm ;STATUS=$((STATUS+$?))
 
+# add initrd/init flags
+mv /initrd/tmp/initflags/* /tmp 2>/dev/null
+rm -rf /initrd/tmp/initflags 2>/dev/null
+
 # kernel modules.builtin/order can also be found in /etc/modules
 # if somehow they're missing from /lib/modules, they will be copied back
 KERNVER="`uname -r`"
-- 
2.9.0

```

**Comment by wdlkmpx** [comment] 2017-09-19 00:59
I have a fix for this... It's quite simple

Ill push It one of these days...

**Closed** 2017-09-22 20:28 UTC
