### ISSUE TITLE
Init script can not find partition with the sfs files if they are stored not in first detected USB drive.

### ISSUE THREAD

**Issue by akhilman** [puppylinux-woof-CE/woof-CE#1877] opened 2020-10-01 13:45 UTC
Init script can not find partition with the sfs files if they are stored not in first detected USB drive.
Same USB drive works fine if I disconnect any other USB drives or if I swap those drives.

Here is log files from failed boot: https://ipfs.io/ipfs/QmYGUpdeTxwyr2kgrZidkW5kk7MW9fmgsFk5fj3q7nYwx4

I can clearly see in logs that during the execution of the init script USB drive with the system was not detected. But I can easily mount that disk as ``/dev/sdc`` immediately after init fault.

``probedisk.log`` does not list ``sdc``
```
/dev/nvme0n1|drive| GIGABYTE GP-GSM2NE3128GNTD|119.2G
/dev/sda|drive|ATA SAMSUNG HD153WI|1.36T
/dev/sdb|usbdrv|Kingston DT Mini 10|7.4G
/dev/sr0|optical|Optiarc DVD RW AD-7191S|1023M
```

Boot partition with grub2 and grub's config is ``/dev/sdc1``, Kernel, initrd and sfs files stored in ``/dev/sdc2``. And grub definitely loads the initrd.
But then init script [calls wait_for_usb function](https://github.com/puppylinux-woof-CE/woof-CE/blob/bb1c0b9f6488b5f94e4ab20f6f8e9873eeaedf87/initrd-progs/0initrd/init#L759), which [calls /sbin/wait4usb](https://github.com/puppylinux-woof-CE/woof-CE/blob/bb1c0b9f6488b5f94e4ab20f6f8e9873eeaedf87/initrd-progs/0initrd/init#L659).

In ``/sbin/wait4usb`` we can see that [it is waiting for the first **any** USB disk](https://github.com/puppylinux-woof-CE/woof-CE/blob/bb1c0b9f6488b5f94e4ab20f6f8e9873eeaedf87/initrd-progs/0initrd/sbin/wait4usb#L23) and solemnly reports that the USB disks are ready.
```bash
CNTUSB=0
USBDRVS="$(find /sys/block -maxdepth 1 -name 'sd*' -o -name 'sr*' | xargs -n 1 readlink 2>/dev/null | grep '/usb[0-9]')"
while [ "$USBDRVS" = "" ]; do
	[ $CNTUSB -ge $TIMEOUT ] && break
	sleep 1
	[ "${1}" ] || echo -en "\\033[1;33m.\\033[0;39m" >/dev/console #yellow dot
	USBDRVS="$(find /sys/block -maxdepth 1 -name 'sd*' -o -name 'sr*' | xargs -n 1 readlink 2>/dev/null | grep '/usb[0-9]')"
	CNTUSB=$(($CNTUSB + 1))
	echo -n " - $CNTUSB" #debug
done
echo
```

I have two solutions in mind. The first one is to wait in the ``/sbin/wait4usb`` until list of USB drives not changes for a 1 second interval. And the second one, much better in my opinion, is to replace the ``wait4usb`` by something like ``wait4part <dev_name|uuid|label>`` and wait for exactly required disks.

Here is forum thread about this issue: https://forum.puppylinux.com/viewtopic.php?f=146&t=966

**Comment by gyrog** [comment] 2020-10-02 11:35
Yes, the problem is with wait4usb returning as soon as  the "fastest" usb device is ready.
Your second solution is the preferred, because then it will wait for any type of device, not just usb ones.
Unfortunately, it is the more difficult to implement, it requires significant changes to the 'init' script.
and it doesn't help if the 'init' script has to resort to searching for the Puppy, you can't wait for a specific device if you do not have some ID for it already.
(I really would like to eliminate "searching" from the Puppy 'init' script.)

I have tried this once for a "normal"  'init', in March  this year, but never got around to adding it to woof-ce.
So I can provide this patch file, if you are interested. The "doing" part happens in a much modified "decode_id()" function.

**Comment by akhilman** [comment] 2020-10-02 13:10
I'm interested in solving this problem, but with a low priority for now. 
If it is not difficult it would be interesting to read your patch.

**Comment by jamesbond3142** [comment] 2020-10-02 13:50
My suggestion is to get rid of the kludges and just go with a parameter called "waitdev=n" where "n" is how long to "sleep", in seconds. 

No need to perform acrobatics detecting whether a USB has been inserted. Use a reasonable value for "n" (5 seconds is enough usually, 3 seconds works but it's a close shave), and anyone for whom the default value doesn't work can simply adjust it up.

This is what we did in Fatdog. I remember Barry carried a few kernel patches just to be able to do this; and I didn't want to carry those patches, and hence the solution. Since it's a general wait command, it will work for all sorts of devices, USB or not.

On Fri, 02 Oct 2020 06:10:43 -0700
AkhIL <notifications@github.com> wrote:

> I'm interested in solving this problem, but with a low priority for now. 
> If it is not difficult it would be interesting to read your patch.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/1877#issuecomment-702725129


-- 
James B

**Comment by akhilman** [comment] 2020-10-02 13:58
> My suggestion is to get rid of the kludges and just go with a parameter called "waitdev=n" where "n" is how long to "sleep", in seconds. 

Agree. Simplicity is the thing I like in Puppy.

**Comment by gyrog** [comment] 2020-10-02 15:12
@jamesbond3142,
Now while it's simple, I would call "waitdev=" a kludge.

It can be implementd so that 'init' waits for any partition that it needs, but it only waits if waiting is it needed, and in every case it only waits as long as necessary.
It does not require any kernel hacks, just waiting until the partition is "visible" in '/proc/partitions' if it's a partition name, or to 'blkid' if it's a volume label or a uuid.
The pain is that the current 'init' algorithm does not easily lend itself to this.

I've been aware of this issue for a while, but it's never been my top priority.

I have attached my 'woof-wait.diff ', just download file and gunzip.
[woof-wait.diff.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/5318771/woof-wait.diff.gz)

**Comment by jamesbond3142** [comment] 2020-10-03 06:36
On Fri, 02 Oct 2020 08:12:55 -0700
gyrog <notifications@github.com> wrote:

> @jamesbond3142,
> Now while it's simple, I would call "waitdev=" a kludge.

I would respectfully disagree.

> It can be implementd to that 'init' waits for any partition that it needs, but only waits if it needed, and in every case it only waits as long as necessary.
> It does not require any kernel hacks, just waiting until the partition is "visible" in '/proc/partitions' if it's a partition name, or to 'blkid' if it's a volume label or a uuid.

Yes, that would work. Instead of waiting for certain kernel events, wait for the actual partition to show up. I think that's what the kernel actually does if you pass the rootwait parameter.

But eventually you need to have a timeout. Otherwise, a simply typo will render Puppy unbootable. It's better to be able to boot, missing the savefile/savedir, rather than hanging completely at boot time waiting for a partition that never shows up.

> The pain is that the current 'init' algorithm does not easily lend itself to this.
> 

I haven't looked at Puppy's init in ages, but can't we just gutted wait4usb and replace it with your suggested changes?

-- 
James B

**Comment by gyrog** [comment] 2020-10-03 10:39
@jamesbond3142,

My code waits for a 1 second interval, with a maximum of 10 iterations, so it can never be an infinite wait.

Hacking wait4usb is not the best way to go, it's not called in the right place, and it's still needed to do it's  current thing while ever 'init' supports "searching".

Using the same technique, I eliminated wait4usb from the 'init' of my "mio" project quite some time ago, but then "mio" does not support "searching".

**Comment by jamesbond3142** [comment] 2020-10-03 13:35
On Sat, 03 Oct 2020 03:39:37 -0700
gyrog <notifications@github.com> wrote:

> @jamesbond3142,
> 
> My code waits for a 1 second interval, with a maximum of 10 iterations, so it can never be an infinite wait.

Excellent.

> 
> Hacking wait4usb is not the best way to go, it's not called in the right place, and it's still needed to do it's  current thing while ever 'init' supports "searching".

I just look at Puppy's init so I'm not totally clueless when responding back to you :)

You're right about wait4usb. I thought wait4usb is a function in init, I just realised it's not. I guess what needs to be done is edit it out and enhance wait_for_usb() instead (I have no idea why wait4usb was farmed out to another file).

> 
> Using the same technique, I eliminated wait4usb from the 'init' of my "mio" project quite some time ago, but then "mio" does not support "searching".

Does puppy has a boot param to specify exact location of the savefile/savedir? If yes we can use your faster solution when it's specified, and fallback to "waitdev" if it's not.

Same case for when loading basesfs file.

cheers!

-- 
James B

**Comment by gyrog** [comment] 2020-10-03 15:23
"normal" Puppy has mechanisms to specify the install location and the save location as a partition,  and a relative path, but the partition spec can be either a name, a Volume label, or a UUID,
so it has a 'decode_id' function to translate whatever is provided into a partition name, this is called for every specified partition.
With the patch, it is in this 'decode_id' function that the waiting is done, if it can't immediately do the translation.

Hmm.. the currrent patch still uses 'wait4usb' when "searching", could be an improvement to use a simple "Sleep n", where the "n" defaults to 5, but can be set via a boot parameter, as per your suggestion.
This would provide a technology agnostic wait, unlike the current 'wait4usb'.

I actually produced this patch a while ago to check problems Puppy had booting from "mmc" drives.

This would provide an incentive for users, and install utility writers, to specify these locations, (since at the time of installation the location of the written files must be known), not a bad thing in my book.

**Comment by jamesbond3142** [comment] 2020-10-04 08:59
Thanks @gyrog for the explanation.

I agree on most of your points about searching; I'd recommend the same as well.

I just want to add that many people however depends on that searching feature. As a comparison, we've got so many "complaints" that Fatdog doesn't find the savefile/savedir just because Fatdog by default searches only on root directory (1-level deep), while Puppy handles this without problem (because puppy searches 2-level deep (root dir and the directories on that root dir)).

So it may not be so easy to get rid of searching feature since many people depends on it.

cheers!

On Sat, 03 Oct 2020 08:23:17 -0700
gyrog <notifications@github.com> wrote:

> "normal" Puppy has mechanisms to specify the install location and the save location as a <partition>,  and a <rerlative path>, but the <partition> spec can be either a name, a Volume label, or a UUID,
> so it has a 'decode_id' function to turn whatever is provided into a partition name, this is called for every specified partition.
> With the patch, it is in this 'decode_id' function that the waiting is done, if it can't immediately do the translation.
> 
> So if  'init' is to continue to support "searching" then what you call "waitdev" would be a more general solution than the current 'wait4usb', since it might be necessary to wait for some storage technologies other than usb.
> I actually produced this patch a while ago to check problems Puppy had booting from "mmc" drives.
> 
> This would provide an incentive for users and install utility writers to specify these locations, (since at the time of installation the location the files that are written must be known), not a bad thing in my book.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/1877#issuecomment-703120046


-- 
James B

**Comment by gyrog** [comment] 2020-10-05 09:42
I have uploaded patched 'init' scripts as replacement 'initrd.gz' files for fosssapup64, scpup32 and scpup64 to [here](http://www.mediafire.com/folder/hkwe9ykjbmvwb/init-wait).

These initrd.gz files have 'wait4usb' removed, since 'init' no longer uses it.
I have implemented jamesbond3142's "watidev" in the "searching" code, (thankyou).

**Comment by gyrog** [comment] 2020-10-05 09:59
@jamesbond3142,
Sprung,  yes, I would dearly love to wean Puppy folk off relying on the  'init' script "searching" to find the Puppy install, but I'm not hanging by my thumbs.

**Comment by jamesbond3142** [comment] 2020-10-05 13:03
Thank you for considering my suggestion, @gyrog .
I hope this gets adopted into mainstream puppies.

cheers!


On Mon, 05 Oct 2020 02:42:40 -0700
gyrog <notifications@github.com> wrote:

> I have uploaded patched 'init' scripts as replacement 'initrd.gz' files for fosssapup64, scpup32 and scpup64 to [here](http://www.mediafire.com/folder/hkwe9ykjbmvwb/init-wait).
> 
> These initrd.gz files have 'wait4usb' removed, since 'init' no longer uses it.
> I have implemented jamesbond3142's "watidev" in the "searching" code, (thankyou).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/1877#issuecomment-703522377


-- 
James B

**Comment by 01micko** [comment] 2020-10-07 10:11
When `/sbin/wait4usb` is removed, there are 2 other scripts that will require `wait_for_usb` call replaced with `wait_for_dev`. They are `/sbin/init-bootmenu` (which is raspi specific for now) and `/sbin/isoboot`.

I'll be testing the former case soon.

**Comment by gyrog** [comment] 2020-10-07 13:13
The simplest way to proceed, would to leave /sbin/wait4usb in  the 'initrd.gz'.
Then these other scripts can work as they do now.
(The reality is that I have no enthusiasm for working on either of those scripts.)

Just a note: I'm not in a hurry to commit these changes to 'init', they need more testing.

**Comment by gyrog** [comment] 2020-10-07 13:34
I have uploaded "-withwait4usb" versions of the "initrd.gz" files [here](http://www.mediafire.com/folder/hkwe9ykjbmvwb/init-wait).
These are the same as the previous ones but have had the '/sbin/wait4usb' file from woof-ce included.
Just to be clear, all of these contain the patched 'init' script, that does not call 'wait4usb'.

**Comment by 01micko** [comment] 2020-10-08 07:33
> I have uploaded "-withwait4usb" versions of the "initrd.gz" files [here](http://www.mediafire.com/folder/hkwe9ykjbmvwb/init-wait).
> These are the same as the previous ones but have had the '/sbin/wait4usb' file from woof-ce included.
> Just to be clear, all of these contain the patched 'init' script, that does not call 'wait4usb'.

`wait4usb` script is called from `wait_for_usb()` function (in `init` script) in both of those scripts. Perhaps I should have been clear about that to save you wasting your time/bandwidth.

Before anything, let me see if the `wait_for_dev` function works in the raspberry pi case (I'll use the slowest pi I have, a pi zero) but I doubt I'll have time before this weekend to post results.

**Comment by 01micko** [comment] 2020-10-10 03:09
Well the initial boot in the pi zero went as expected. There was the wait message before the boot gui appeared and then another when the init proper started. The partition resize went as expected.
I set things up and rebooted and got a breif wait message before boot gui but none thereafter. Subsequent boots were the same. All working as expected.`wait_for_dev` replaced `wait_for_usb` as mentioned above. Typing on pi zero now.

**Comment by gyrog** [comment] 2020-10-10 12:03
@01micko,
If my changes to 'init' were committed,  and your changes to the other scripts were committed, we could remove the file '/sbin/wait4usb' from 'initrd.gz'?
Being a little cautious, we could work on changing the scripts now, and remove '/sbin/wait4usb' later.

**Comment by gyrog** [comment] 2020-10-10 12:12
Unfortunately I have an "improved" 'init' script.
I uploaded new initrd.gz files noted with a "+cd" in  the filename, [here](http://www.mediafire.com/folder/hkwe9ykjbmvwb/init-wait).
This provides a 'wait_for_blkid()' which can be used for other queries of blkid, apart from 'decode_id()'.
This 'init' includes an example of this, when "pmedia=cd", 'wait_for_blkid()' is called to get a list of 'iso9660' partitions, and if there's only 1, it uses that as the Puppy install partition, (does not "search").

**Comment by 01micko** [comment] 2020-10-10 12:18
Why don't we create a new branch for these experiments? I can release an experimental slacko iso and an experimental raspup image from said branch. We really need more use cases to evaluate.

**Comment by gyrog** [comment] 2020-10-10 14:02
Ok.
What should it be called "wayoutthere"? (joking)
"testing" seems to be already in use.

**Comment by Butterfly** [comment] 2020-10-10 18:45
@gyrog said.. 
> What should it be called "wayoutthere"? (joking)
> "testing" seems to be already in use.

@01micko previously stated..
> Why don't we create a new branch for these **_experiments_**? I can release an **_experimental_** slacko iso and an **_experimental_** raspup image from said branch. We really need more use cases to evaluate.

Meanwhile, @Butterfly is grinning while watching it transpire.. :laughing: 

Experimental is actually [a thing over at Debian](https://wiki.debian.org/DebianExperimental). I just installed from there for the first time a couple weeks ago. I think it was my `wicd` network manager.

With an understandable lean toward an operating system doing its own thing, I took a poke at [Thesaurus' synonym recommendations](https://www.thesaurus.com/browse/experimental?s=t) for "experimental." That landed four words that had possible potential: Pilot, trial, developmental, and laboratory. Personally, I like that "laboratory" because I haven't noticed it anywhere (yet).

The word "futuristic" also came to mind. [Its synonyms include](https://www.thesaurus.com/browse/futuristic?s=t): Innovative, advanced, cutting edge, pioneering, and visionary.

In keeping with the canine theme, maybe a search for something like "experimental dog training terminology" might land something that Developers would enjoy referencing over time. :dog:

**Comment by 01micko** [comment] 2020-10-11 02:30
I created new branch `init-experiment`. @gyrog feel free to commit whatever you see fit. IMHO `/sbin/wait4usb` can go and we deal with the fallout later.

**Comment by gyrog** [comment] 2020-10-12 03:36
Ok, I'll respond here to advise what changes I have made.

**Comment by gyrog** [comment] 2020-10-12 05:08
I've committed a "wait" patch and a "cd" pach to the 'init' script, with comments on the commit.
So the 'init' in 'init-experiment' is the same as in the initrd.gz files I released earlier.

Later Edit: And I removed file '/sbin/wait4usb'.

**Comment by 01micko** [comment] 2020-10-12 09:20
@gyrog .. just tag your commit comments with #1877 which saves you posting here every time you make a commit.

**Comment by peabee** [comment] 2020-10-16 08:42
UPupGG+D-Alpha+4 has been built using init-experiment ......
BUILD_FROM_WOOF='init-experiment;8f4c1e337;2020-10-12 19:10:19 +1000'
https://sourceforge.net/projects/zestypup/files/Upup-Groovy%2B/alpha/

**Comment by gyrog** [comment] 2020-10-16 11:01
@peabee,
Thanks, I'll give it a go.

**Comment by 01micko** [comment] 2020-10-18 07:31
[eSlacko64](https://forum.puppylinux.com/viewtopic.php?p=7862#p7862)

**Comment by gyrog** [comment] 2020-10-30 13:14
I've committed a number of patches to 'init-experiment'.
These are mostly to do with improved 'isoboot' support, which now includes support for a "iso_dev=" boot parameter, that allows for identifying the partition that contains the ISO file, to the 'init' script.

@01micko, sorry, I was so focused on what I ws going to call these commits that I forgot to add #1877

**Comment by peabee** [comment] 2020-11-10 07:23
@gyrog 
@01micko 
Can init-experiment be merged back into testing now?

**Comment by gyrog** [comment] 2020-11-10 09:55
'init-experiment' now contains all my patches for dealing with "waiting" in 'init'.
I am not aware of any "problems" with the code, I had a scare with "UPupGG+D-Alpha+4" , but that turned out to be an 'f2fs' issue. 
(The boot failed because I put the "install directory" on an f2fs partition, but 'f2fs' support was in a module.This is all fixed in 'UPupGG+D-20.10+0.iso'.)

Short answer: I have no problem with the current changes being transferred to 'testing' branch.
Although there may be some push-back for some. e.g. commit 2df868e.

The changes to the actual "waiting" methodology, provide improvements without noticeable side-effects:
For frugal installs, there should be no obvious changes, except support for some situations that did not work before, e.g, multiple usb devices sometimes did not work.

BUT, some changes are more noticeable:
For CD booters, commit 2df868e, the first "iso9660" is expected to contain the install directory, rather than using the "search_func".
For 'isoboot' users, commit 5057f0d, the intergration with the rest of  'init' is different, the new code takes advantage of the establishing the location of the install directory within 'isoboot' and sets appropriate variables to "fool" the rest of 'init'.

Although I wouldn't mind if the 'init-experiment' branch remained for a while.
I  have a number of changes to 'init' and 'shutdownconfig' in my pipeline in relation to #1867.
My current intention is to apply these to the 'init-experiment' branch if it is still available.
But I will not "contaminate" the 'init-experiment' branch until I get the impression that the "waiting"  stuff is "accepted".

**Comment by 01micko** [comment] 2020-11-10 11:14
IMHO, taking into account @gyrog 's last response, it can be merged but kept alive for future related experimentation.

My tests have proved sane in slacko booting on various media and in raspup booting from sd card.

**Comment by gyrog** [comment] 2020-11-10 11:55
@01micko.
Thankyou.

Excuse my git ignorance, but how is a "merge" done, and who is to do it?

I could do it the long way, I have patch files that repesent each of the commits, so I could "checkout"  the 'testing' branch, and do new commits to 'testing', but I suspect that's not a real git "merge", and it would not include @01micko's commits.

**Comment by 01micko** [comment] 2020-11-11 02:46
Anyone who has write access to woof-CE repos can merge. As for "who should", well whomever deems it necessary. Obviously that user should be confident to do it.

Another way is to open a pull request for the branch, but I'm not sure if anyone can do that (possibly) or it has to be the creator of that branch (me).

---

IIRC this is how to merge:

Say your local branch is currently on origin/init-experiment. I'll assume that is up to date since you were last to commit.

switch to testing

```
git checkout testing
```

then merge

```
git merge init-experiment
git push origin testing
```

BUT...

There are pull requests open on testing that are worthy of merging to do with pulse audio and the like and PPM from @rizalmart 

I'll go through these PRs later today and merge what is necessary then consolidate init-experiment. It is important to keep both active branches up to date with each other in relation to the fork point. It avoids merge conflicts down the track.

**Comment by 01micko** [comment] 2020-11-11 03:18
@gyrog I have merged the necessary PR's to testing and consolidated init-experiment by merging testing into it. Now it is a matter of just merging init-experiment back into testing. I'll leave it to you.. just remember your local branch of init-experiment is now behind the remote. :wink:

**Comment by gyrog** [comment] 2020-11-11 07:43
@01micko, Thanks.
I've done:
git pull on init-experiment
git checkout testing
git pull on testing

So I'm ready to go with "merge" and "push"?

Am I right in assuming that I need to do this before any more "pull" requests are made against 'testing'?
Otherwise the whole "consolidate" process needs to be done again.

**Comment by 01micko** [comment] 2020-11-11 08:23
yep @gyrog sounds right.

Once merged do 
```
git log
```

on testing to see if it seems sane. Then push to `testing`

Thats it.

**Comment by gyrog** [comment] 2020-11-11 08:46
Done.

**Comment by 01micko** [comment] 2020-11-11 09:17
@akhilman the OP. Have you tried any of the releases mentioned in this thread? If so, is your issue solved?

Many thanks @gyrog @peabee and @jamesbond3142

**Comment by 01micko** [comment] 2020-11-11 10:23
@gyrog there are new commits to `testing` which I have merged to `init-experiment`

**Comment by akhilman** [comment] 2020-11-11 11:04
UPupGG+D-Alpha+4  built using init-experiment works fine for me.

**Comment by gyrog** [comment] 2020-11-11 11:45
@akhilman, great.
@01micko, thanks, I've got them with a "git pull".

**Comment by 01micko** [comment] 2020-11-11 12:01
@akhilman thanks. Then we can close this thread and @gyrog I suggest to open a new issue for relevant `init-experiment` ideas so we can further discussion.

**Closed as completed by 01micko** 2020-11-11 12:01 UTC

**Comment by gyrog** [comment] 2020-11-11 12:13
My next project for 'init-experiment' will be in the following issue:
shutdownconfig: bug + SAVESPEC enhancement + autosave enhancement #1867
