### ISSUE TITLE
pmount "feature" with rox

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1205] opened 2018-05-16 09:10 UTC
rox window needs to be reloaded after 2nd mount....??
http://murga-linux.com/puppy/viewtopic.php?p=991009#991009
http://murga-linux.com/puppy/viewtopic.php?p=991020#991020

**Comment by wdlkmpx** [comment] 2018-05-16 13:41
i don't use rox as a file manager, but i'll see what i can do

reading the same page, this seems to be an issue with probedisk:
```
One small problem with pMount (yes, another one I'm afraid!). I've set the pMount window to have the tabs for categories, instead of all in one window. Strangely, the external USB HDD is not showing up under the 'usbdrv' tab.....it's showing-up under 'optical'? Which probably explains why it wasn't showing in the main, single window..... 
```

that should never happen.. i tested probedisk with optical and hdd usb drives. 

but without the output of probedisk and probepart it will remain a complete mystery

**Comment by wdlkmpx** [comment] 2018-05-16 16:37
fixed in https://github.com/puppylinux-woof-CE/woof-CE/commit/f2a94cb9639141eaa1ef0e3cd67dac91605b4681

i think opening pull requests to master is ok. i'll keep master and testing in sync for some time until a brutal change lands on testing..

as @woodenshoe-wi is patching rox, the question.. is it possible to implement this in rox:
- silently close a window when the directory is deleted, to avoid using -D
- update directory when a second "instance" tries to open it again (to avoid -x), although  just making the window get the focus is enough...

these 2 changes are enough to delete  a lot of hacks everywhere. but that would mean ONLY a woofce-specific rox will properly work with the wce system... and that's fine i think..

**Comment by woodenshoe-wi** [comment] 2018-05-16 22:57
I'm no expert on the inner workings of ROX, but in my tests when I delete a directory from the command line that is currently open in a ROX filer window it immediately adds "Can't stat directory: No such file or directory" in the title bar but doesn't pop up the error dialogue and disappear until I put the mouse over it.  This seems to suggest that the first change should be possible if the code that pops up the dialogue and closes the window could be moved to the place where the title bar is updated.  Where that is and how involved the changes would be, I don't know right now.

If I make or delete a file or directory from the command line the change shows up immediately, so I am not sure what is causing the second issue or how to test it.

If the changes can be made in a clean way, and jun7 would be willing to merge them, people could still choose which fork of ROX that they want to use.

The issue for me is that when I start writing c code it usually comes with segfaults.  As I keep working on it I find most of them, but there still might be some left.  Now when someone is testing a new program that they know might have problems it's not that big a problem, but peabee knows first hand what happened when my findpkgs helper programs were suddenly made the default.

I would be more comfortable if there was some way to get people to volunteer to test my version of ROX and look for problems before suddenly making it the woof-CE default and only choice.

**Comment by wdlkmpx** [comment] 2018-05-17 04:31
the issue reported by mike walsh was a pmount bug. fixed in https://github.com/puppylinux-woof-CE/woof-CE/commit/7e08a9a50d9e19f72fccf527bd268c50892017e9

another important bugfix in https://github.com/puppylinux-woof-CE/woof-CE/commit/584fa50905fa477956512108a6b9e569287d3229

yeah getting people to test something is certainly the most difficult part. i remember opening threads and asking people to do something, i realised i needed some kind of authority that i didn't have..

**Comment by wdlkmpx** [comment] 2018-05-17 20:32
Yeah i'd download the pet pkg and test a bit

**Comment by woodenshoe-wi** [comment] 2018-05-18 04:00
This might be a dead end...

I have been looking at the code and I can get the window to close when the directory is deleted, but I get an error and then ROX segfaults.

```
# ROX-Filer/AppRun -n

** (ROX-Filer:2773): CRITICAL **: dir_detach: assertion 'in_callback == 0' failed
Segmentation fault
```
The problem is that the process that updates the title bar starts with the `dir_rescan` function in dir.c setting the dir->error string and then calling a callback function `update_display` in filer.c

Trying to use `gtk_widget_destroy(filer_window->window);` from the callback function gives an error because when the window is destroyed the `filer_window_destroyed` function in filer.c is called, which in turn calls the `detach` function in filer.c which calls the `dir_detach` function referenced in the error.

The `dir_detach` function has a line `g_return_if_fail(in_callback == 0);` near the beginning, so I'm assuming trying to run it from a callback is not going to be possible.

The reason the window can be closed by the "Directory missing/deleted" message box is that the `may_rescan` function in filer.c is called from the `pointer_in` function in filer.c which is an event handler, not a callback function.

I don't think I am enough of an expert on gtk event driven programming to figure out how to get a window to close itself without segfaulting.  It might be possible to do something with SOAP/RPC/IPC but I would have to figure it out first.

**Closed** 2018-05-18 18:17 UTC

**Comment by woodenshoe-wi** [comment] 2018-05-18 18:58
I started investigating the other approach using SOAP and it seems to work without errors or segfaults.  The only strange behavior I found so far is that if the last window is closed by deleting the directory ROX keeps running without any windows visible :grinning: Not a serious problem.

**Comment by woodenshoe-wi** [comment] 2018-05-18 21:11
Links to pets are at [http://murga-linux.com/puppy/viewtopic.php?p=992429#992429](http://murga-linux.com/puppy/viewtopic.php?p=992429#992429) :grinning:

**Comment by wdlkmpx** [comment] 2018-05-18 21:38
Testing pmount: mounting and unmounting a partition. The rox window is
automatically closed when the partition is unmounted (and the
directory is deleted).

It works. 'rox -D' will not used in the rootfs scripts (in the future)..

**Comment by wdlkmpx** [comment] 2018-05-18 22:03
'-s' is to highlight a file
'-x' is to re-examine a file
'-d' is to open a directory as a directory. this opt is recognized by
pcmanfm (daemon mode)

I'm not aware of any other file manager with such advanced options to
open directories, so i'll carefully remove those switches where
appropriate..

**Comment by woodenshoe-wi** [comment] 2018-05-20 05:53
Some of the "advanced options" might have been necessary in the days before dnotify and inotify.

Are you sure that version 2 works for you?  When I was testing it some more I found that if I opened a terminal by pressing the \` key, when I exited the terminal ROX would close ALL filer windows.

Fixed it in version 3, [http://murga-linux.com/puppy/viewtopic.php?p=992606#992606](http://murga-linux.com/puppy/viewtopic.php?p=992606#992606)

**Comment by woodenshoe-wi** [comment] 2018-07-01 17:45
Under certain circumstances a missing directory might not be closed every time, so some more changes might be needed before it is completely ready.

**Comment by wdlkmpx** [comment] 2018-07-01 19:58
As long as it doesn't segfault.. everything's ok.

NAMEONLY and VERSION.. new cli options can be added, however the
source tarball filename should be something like this

rox-filer-5woodenshoe.tar.gz

The resulting pet pkg would look like this:

rox-filer-5woodenshoe-i686_common32.pet

PET PKG.. it's simple.. delete the rox-filer petbuilds in other
branches than generic or replace the petbuilds with the woodenshoe
one.

ROOTFS: add either rox_config to rootfs-packages or stuff to
rootfs-skeleton. rox_config should be automatically selected if
'yes|rox-filer' or grep '|rox-filer|'

To fix this ASAP, a fixed rox-filer pkg can be uploaded to the common
pet repos and arm pet repo.. and enforced in woof-distro. i don't know
if a pkg like rox-filer qualifies for the 'common' repos..

Now, when it comes to rox_config, it would need some better defaults.
I certainly have to retrain my brain when i use rox, i try not to
press ctrl+x when i want to 'cut' a file.. it would be deleted, the
defaults are too different from what you see everywhere else..

There is also the issues with shared-mime-info, file associations and
icons. For file associations, /etc/pmime.conf provides some valuable
info. aaa/bbb = aaa_bbb. This is something that should be fixed ASAP
as well.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/694cbefd5f4ac902b90dbd7dc4f9c6e06d369b54
also sheds some light on the subject

**Comment by woodenshoe-wi** [comment] 2018-07-02 03:49
> i don't know if a pkg like rox-filer qualifies for the 'common' repos..

Well, I've been compiling it using the same method as the rest of the common apps...

> I certainly have to retrain my brain when i use rox, i try not to
press ctrl+x when i want to 'cut' a file.. it would be deleted, the
defaults are too different from what you see everywhere else..

I figured out how to change the 'Delete' key binding to the 'Delete' key, so ctrl+x actually will 'cut' the file to the clipboard in my fork.  I got copy/paste using the clipboard working too.

I will try tagging the version backwards if that is the way you want it.  I'm not interested in doing things ASAP, but more like slow and steady... I will work on things as I have time, and as the GPL license says 

> "AS IS" WITHOUT WARRANTY OF ANY KIND

So no promises that it won't segfault under some combination of circumstances that I didn't test 😁

**Comment by woodenshoe-wi** [comment] 2018-07-02 05:49
@peabee I'm leaving this to your discretion if you want to upload these pets to ibiblio...  
I have **NOT** tested these in woof builds, only by installing the derived standalone pets into existing installs.

The problem with the package list entry names has been solved.  They are now just `|rox-filer|`

https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common32/rox-filer-6woodenshoe-i686_common32.pet
https://gitlab.com/woodenshoe-wi/petbuilds-out/raw/master/puppylinux/pet_packages-common64/rox-filer-6woodenshoe-x86_64_common64.pet

I think you know the direction wdlkmpx wants to go with making them the "enforced" version.

If you don't want to add them to ibiblio until they get some testing it should be possible to include them in test builds following the instructions at http://murga-linux.com/puppy/viewtopic.php?p=992429#992429

**Comment by peabee** [comment] 2018-07-02 08:31
I think an experimental woof-ce build is needed so that others can test and feedback feelings....
Should probably be a combined rox-filer-6woodenshoe-i686_common32 and overlayfs experiment - maybe?
