### ISSUE TITLE
Issues with EFI/grub2 and 4.19.X kernel

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#1503] opened 2019-07-24 02:51 UTC
Testing recent Woof-CE builds of BusterPup and Dpup Stretch:

In BusterPup Beta-1 and Dpup Stretch RC5, foxpup describes a normal boot sequence when he utilizes a pendrive and grub4dos with one or multiple pupsave files.

However, with recent iterations of the 4.19.X kernel, when foxpup boots his SSD drive (SAMSUNG MZYTY256) with EFI/grub2 and multiple pupsaves, the usual list of selectable pupsaves does not appear on screen, so no way to choose the desired pupsave file. He has no problem when booting with EFI/grub2 and one pupsave.

Interestingly, on his EFI/grub2 installations of BusterPup and Dpup Stretch (with multiple pupsaves), the list of selectable pupsaves appears as expected when he boots with the 4.9.X kernel (such as 4.9.149) or with older iterations of the 4.19.X kernel (such as 4.19.26).

I have no experience with grub2, but booting BusterPup on my SATA drive with legacy grub and multiple pupsaves works fine for me.

For testing, I have now recompiled the 4.19.56 kernel with the same EFI config options as 4.9.149, but this does not help foxpup. Also, reverting to an older init does not help.

Any thoughts? Why would the list of selectable pupsaves fail to a appear when foxpup boots his SSD drive with EFI/grub2 and multiple pupsaves (using the recent 4.19.56 kernel)?

foxpup's original posts:
http://murga-linux.com/puppy/viewtopic.php?p=1032329#1032329
http://murga-linux.com/puppy/viewtopic.php?p=1032412#1032412

**Comment by wdlkmpx** [comment] 2019-07-24 17:14
If the new initrd stuff is not to blame, then probably an upgrade to grubx64.efi might fix it. Or maybe it's a kernel regression, who knows..

I guess the file path is /EFI/boot/bootx64.efi (in the ssd/usb drive)

[grubx64.efi_2.04.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3428009/grubx64.efi_2.04.gz) from Debian sid

Rename to grubx64.efi to bootx64.efi

**Comment by f0xpup** [comment] 2019-07-24 21:25
I've tried the grub2 binary from debian. It expects grub.cfg to be in /EFI/debian/, as to be expected. I had to correct for that in my setup on ssd.
It does not solve the lag of the boot messages. 
It boots pretty much like my own grub2 binary.
Btw, I compiled a grub2 binary to my likings in Slackware some time ago.

I have also tried kernel 5.2.1-lxpup64 (from the huge kernels on archive.org) for busterpup and that works perfectly, no lag for the boot messages, they come up immediately.

It is not entirely true that I have "no problem when booting with EFI/grub2 and one (1) pupsave". Even then the boot messages don't come on the screen for a while.
This may explain it better:
[http://murga-linux.com/puppy/viewtopic.php?p=1032872#1032872](http://murga-linux.com/puppy/viewtopic.php?p=1032872#1032872)
> It is just the boot messages that do not appear.
> In the end all messages appear at once.
> The last line, from where the queue continues, is "loading kernel modules".

**Comment by wdlkmpx** [comment] 2019-07-24 21:33
It's probably a kernel bug in the k4.19 series

**Comment by wdlkmpx** [comment] 2019-07-29 17:59
I downloaded busterpup and I can confirm the bug, booting from  usb and i haven't created a pupsave but i see the grub2 splash img does not disappear, there's a long delay and stuff is printed after switch_root i think.

One thing i noticed is that this is a fairly recent build and the multiarch symlink is there... that symlink was killed two or 3 months ago
https://github.com/puppylinux-woof-CE/woof-CE/commit/9990e333e3f536a9d9e0cf327df225a5e53a846b

I have issues with this pup, i don't know maybe it's cherry-picking changes. I don't know.

**Comment by wdlkmpx** [comment] 2019-07-29 18:22
The initrd is certainly "older" than what is to be expected from 
BUILD_FROM_WOOF='testing;0d2cf1e6e;2019-07-08 19:14:24 +1000'

In may 27 the directory layout changed
https://github.com/puppylinux-woof-CE/woof-CE/commit/778c5205adec436db2e5fea1e4c90324c60a7b2a#diff-4eb4a900a7b6f2ab7a334cb6ec1983c3

It's probably the kernel, maybe aufs causes some disturbance (in the force), or maybe it should have less builtin modules, maybe more exotic filesystems as .ko modules and less exotic processes running by default..

So, i'll try to figure out what's wrong, but this is confusing. That's why i try to deal only  with stuff that is in the woofce repo, and nothing else.

**Comment by wdlkmpx** [comment] 2019-07-29 18:51
I also noticed my engrampa version is used in this pup. I never released a engrampa package, so this probably comes from dpup stretch.. the massive w_apps package.

The best i can do is create a dpup buster in woofce, and convert the massive w_apps to individual packages and update all the x86 pups, so that you'll find most stuff in order, and then add jwm3config (disables ptheme) and extra apps. There's no need to use old woofce stuff in a "recent" builds ..

**Comment by radky2** [comment] 2019-07-29 20:26
Concerning foxpup's issue with EFI/grub2 in BusterPup, it seems my DOTconfig for k4.19.X was missing a framebuffer configuration option. This is now fixed, and foxpup reports success booting BusterPup with EFI/grub2. My apologies for not noticing this earlier.

---

@wdlkmpx,

BusterPup has been in development for six months with extensive testing and innumerable bug fixes. I have used most commits available in 'Woof-CE testing' through early June, and have added various cherry-picked commits after that date.

When the 'experimental' branch was recently added to the 'testing' branch, I was hesitant to add all new commits en bloc since this would require another round of extensive testing before I would be confident of a stable release. I apologize for any misunderstanding. If I have the good fortune to develop another Puppy, I will include the most recent Woof-CE commits available at that time.

Concerning engrampa currently in BusterPup, yes it is from Stretch.

Thank you wdlkmpx for the many recent improvements in Woof-CE.

**Comment by wdlkmpx** [comment] 2019-07-29 20:54
Well, there have been some significant bugs since the experimental
branch was merged.

However it's fairly stable now... i think...

When big changes are added, i guess it's reasonable to be wary of
them, and waiting two or three months before releasing something might
be the way to go.

However it's thanks to those who test all the latest changes and
provide feedback that things become stable again.

The changes in the experimental branch were fairly tested, i spent
many hours testing, i really doubt i'll be able to do something like
that again. The list of changes is very extensive.

I'll use your configs for the woofce dpup buster, or busterpup. I'll
take a look and see what other apps i should add to the common*
repos...

**Comment by radky2** [comment] 2019-07-29 21:26
The upcoming BusterPup Beta-2 will include updates for DISTRO_PKGS_SPECS plus the corrected DOTconfig for k4.19.X.

Thank you wdlkmpx.

**Closed as completed** 2019-08-04 14:29 UTC
