### ISSUE TITLE
QEMU packaged for WoofCE 

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2070] opened 2021-03-04 00:33 UTC
**_Looking thru the forum_**

There is an outstanding request on the forum **[here](https://forum.puppylinux.com/viewtopic.php?p=18159#p18159)** asking for an updated QEMU to be awarded. 

As the WoofCE teams moves to it upcoming distro versions, could v5.2+ be added?

Thanks for considering
P.S. GRUB2 utilities would be a good addition to the 64bit PUPs.

**Comment by 01micko** [comment] 2021-03-04 07:45
duplicate of #2069 

It _really_ is a maintainer issue. We all do our best :smile_cat:

**Closed as completed by 01micko** 2021-03-04 07:45 UTC
