### ISSUE TITLE
extrasfs fail to load at startup in VDpup 10.0.43

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#3489] opened 2022-10-11 20:08 UTC
As the title says.
The sfs is written in BOOTCONFIG but never loads, not is shows in the console during the boot process.
Loading manually ot viewing is OK but still not present after reboot.

**Comment by dimkr** [comment] 2022-10-12 05:29
Please attach BOOTCONFIG and /initrd/tmp/bootinit.log

**Comment by mavrothal** [comment] 2022-10-12 05:52
Attached
[BOOTCONFIG.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/9761877/BOOTCONFIG.zip)
[bootinit.log.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/9761878/bootinit.log.zip)

**Comment by dimkr** [comment] 2022-10-13 07:22
Can you reproduce this against 10.0.44 with `loglevel=7` and attach bootinit.log?

**Comment by mavrothal** [comment] 2022-10-13 07:48
I will some time tonight  but till then I was looking at it briefly and looks like that ```setup_onepupdrv``` returns ```3``` for empty file at ```/mnt/pdrv/<filename>.sfs``` where ```find_onepupdrv``` mounts it.

**Comment by dimkr** [comment] 2022-10-13 07:52
I'm not sure I understand - why would this file be empty, and how can it be mounted if it's empty?

**Comment by mavrothal** [comment] 2022-10-13 08:35
The sfs
 is NOT empty (you can actually click on it and see its content)
May be something in the ```setup_onepupdrv``` logic
Do extra SFSs mount OK for you (or others)?

**Comment by mavrothal** [comment] 2022-10-13 08:38
Wasn't at some point that the extrasfs mounting moved (for aufs builds) to the rc.sysinit or I remember something else?

**Comment by dimkr** [comment] 2022-10-13 08:57
> Do extra SFSs mount OK for you (or others)?

It used to work, but I can't rule out the possibility of a regression.

> Wasn't at some point that the extrasfs mounting moved (for aufs builds) to the rc.sysinit or I remember something else?

If SFS loading is moved to rc.sysinit, it won't with with overlay unless it's implemented using some inefficient trick (like #3398).

**Comment by mavrothal** [comment] 2022-10-13 10:05
I think the problem is in ```setup_onepupdrv``` that while the sfs is mounted in ```/mnt/dev_save/<filename>.sfs```, is looking for it in ```/mnt/pdrv/<filename>.sfs``` and ```/mnt/pdrv``` does not exist!
This is because ```find_drv_file``` sets ```"$3"``` as ```p```  but pdrv was never made.

**Comment by dimkr** [comment] 2022-10-13 16:11
Looks fine here:

![sfs](https://user-images.githubusercontent.com/1471149/195649300-0d1ab17a-712a-4711-bd7b-f1819b895f69.png)

This VM boots from the ISO, saves to /dev/sda1 and a.sfs sits in /dev/sda1. The SFS is loaded and works.

**Comment by mavrothal** [comment] 2022-10-13 17:21
I boot from a usb stick and Dpup is in a VFAT partition with a savefile
and I can get that far too
```
+ '[' sdb3 -a overlay '=' overlay -a -f /pup_new/etc/rc.d/BOOTCONFIG ]
+ EXTRASFSLIST=
+ . /pup_new/etc/rc.d/BOOTCONFIG
+ EXTRASFSLIST=dkms.sfs
+ PREVUNIONRECORD='vanilladpupsave-Xorg.4fs puppy_vanilladpup_10.0.43.sfs fdrv_vanilladpup_10.0.43.sfs zdrv_vanilladpup_10.0.43.sfs bdrv_vanilladpup_10.0.43.sfs kbuild-5.19.11.sfs'
+ LASTUNIONRECORD='vanilladpupsave-Xorg.4fs puppy_vanilladpup_10.0.43.sfs fdrv_vanilladpup_10.0.43.sfs zdrv_vanilladpup_10.0.43.sfs bdrv_vanilladpup_10.0.43.sfs kbuild-5.19.11.sfs'
+ losetup -f
+ LOOP=/dev/loop6
+ find_onepupdrv sdb3  dkms.sfs p 1
+ ONE_FN=
+ '['  ]
+ '[' dkms.sfs ]
+ '[' p ]
+ '[' sdb3 ]
+ ONE_PART=sdb3
+ '[' sdb3 ]
+ ensure_mounted sdb3 /mnt/pdrv
+ grep -m1 '^/dev/sdb3 ' /proc/mounts
+ cut -f 2 -d ' '
+ ONE_MP=/mnt/dev_save
+ '[' /mnt/dev_save ]
+ grep -m1 '^/dev/sdb3 ' /proc/mounts
+ cut -f 3 -d ' '
+ ONE_FS=vfat
+ return
+ '[' /mnt/dev_save ]
+ find_drv_file  dkms.sfs 1
+ ONE_FN=
+ '['  ]
+ '[' dkms.sfs ]
+ '['  ]
+ ONE_TRY_FN=/Dpup_10X/dkms.sfs
+ '[' 1 -a '!' -e /mnt/dev_save/Dpup_10X/dkms.sfs ]
+ ONE_TRY_FN=/dkms.sfs
+ '[' -L /mnt/dev_save/dkms.sfs ]
+ '[' -f /mnt/dev_save/dkms.sfs ]
+ ONE_FN=/dkms.sfs
+ '[' /dkms.sfs '='  -a  ]
+ '[' /dkms.sfs ]
+ LOADMSG=extra
+ setup_onepupdrv sdb3,vfat,/dkms.sfs ro6 p
```
(though looks like i have one more loopmount)
The failure is immediately after
```
+ ONE_LAYER=
+ echo sdb3,vfat,/dkms.sfs
+ cut -f 1 -d ,
+ ONE_PART=sdb3
+ '[' sdb3 ]
+ echo sdb3,vfat,/dkms.sfs
+ cut -f 3 -d ,
+ ONE_REL_FN=/dkms.sfs
+ '[' /dkms.sfs ]
+ ONE_SFX=ro6
+ ONE_PREP=p
+ '[' sdb3 '=' rootfs ]
+ '[' sdb3 '=' sdb3 ]
+ ONE_MP=/mnt/pdrv
+ ONE_FN=/mnt/pdrv/dkms.sfs
+ basename /dkms.sfs
+ ONE_BASENAME=dkms.sfs
+ '[' -s /mnt/pdrv/dkms.sfs ]
+ return 3
```

**Comment by mavrothal** [comment] 2022-10-14 08:40
The problem with ```setup_onepupdrv``` is that is hard coded to look at ```/mnt/pdrv/``` but  is not linked to ```/mnt/dev_save``` that is actually mounted at the time.

**Comment by gyrog** [comment] 2022-10-14 14:43
Everr since "rationalise", extra-ssfs is no longer processed by 'init'.
It's left to 'sfs_load' run in 'rc.sysinit, (for aufs)

Extra-sfs pocresing has had to be added to 'init' for overlayfs.

**Comment by mavrothal** [comment] 2022-10-15 11:36
I do remember then!
Can someone with time "irrationalise" the init a bit...
Also do release dpup 10.X with bugs and everything, so it can get some real life testing.

Wayland btw behaves much better than X on the mac.

**Comment by dimkr** [comment] 2022-10-15 12:07
> Also do release dpup 10.X with bugs and everything, so it can get some real life testing.

Some people are already using 10.0.x development builds and things start to look really good.

I'll create a stable woof-CE branch for 10.0.x and start releasing beta releases with an organized changelog and all when the Debian 12 freeze starts at January.

Until then, the focus is fixing, testing and verifying:
1. Wayland, especially what's under https://github.com/puppylinux-woof-CE/woof-CE/projects/1:
#3448
#3467
#3454
#3322
#3030
If Debian 12 ships with wlroots 0.16.0, I believe most Wayland-specific issues will disappear without extra work; but if it doesn't, I'll need to rebase the dwl patches and link it statically with wlroots 0.16.0. I'll consider dropping the X.Org flavor if the Xwayland flavor works for 80% of users.
3. overlay:
#3348
#3326
#3183
#3398
#3402
plus bugs like this one
5. Proper support for file managers other than ROX-Filer and decoupling woof-CE from ROX-Filer: #3500
6. Ease of maintenance, more automation and reduction of technical debt:
#3365
#3431
#3325
9. General performance, resource consumption and boot time improvements
#3461
#3475
#3452
#3442
#3440
#3439
#3499
10. Security, especially for applications running as spot
#3419
#3484
11. Even more Debian compatibility
#3435
#3487

**Comment by mavrothal** [comment] 2022-10-15 19:17
In case is of any help I digged some old VMs and both Dpup 22.03 (woof 2022-03-21) and Upup22.04 (woof 2022-04-21) boot extra SFSs from ext4 of VFAT drives without problem
I guess that init streaming/clean up done at some point later, messed this function somehow 

PS: These older init scripts load the extrasfs list fine with 10.0.43, when ```UNIONFS``` is set to ```overlay```

**Comment by dimkr** [comment] 2022-10-19 06:10
@mavrothal Now I see that! Yes, the logic there is broken with all that `ONE_MP=` mess and that `ensure_mounted` nonsense. The init script is the worst piece of shell scripting I've ever seen, with all those global variables, cryptic names and what not. It's impossible to work with but kind of works, so I'll see if I can fix it without any refactoring first.

**Comment by mavrothal** [comment] 2022-10-19 06:38
Oh, c’mon... the puppy ```init``` script was one of its trademarks, doing (too) many things in (too) many ways.
@gyrog ’s rewrite tried to both stream-line, textedit it, provide more file location flexibility (and moved extra SFSs to the main) and provide some additional functionality (as kernel module loading in early boot)
Now overlay comes into play and extra SFSs must be brought back in. 
That's all!
I did not follow ```init``` development through "rationalize" and indeed is not easy to catch up given the time I (do not) have.
But I believe should not be difficult for @gyrog or you

**Comment by dimkr** [comment] 2022-10-19 06:45
Maybe it would be just easier to rewrite it. I added snapmergepuppy**.overlay**,  sfs_load**.overlay** and so on because the aufs originals hand thousands of lines, had a very messy coding style and did ugly things like re-running themselves.


For example, now sfs_load (2526 lines) lets sfs_load.overlay (190 lines) handle the situation when using overlay:

```                                                                                                           
if [ "$PUNIONFS" = "overlay" ] ; then                                                                       
        exec sfs_load.overlay "$@"                                                                          
fi                       
```

Maybe I'll just copy initrd-progs/0initrd/init aside, drop all overlay-related things from initrd-progs/0initrd/init, which is almost the same as reverting all changes and including #2963, then write a super simple replacement called init.overlay which handles just PUPMODE 5, 12, 13, without any extra features.

**Comment by gyrog** [comment] 2022-10-19 13:03
@mavrothal,
Are you using aufs or overlayfs?

If aufs, then it's not an init issue, it's an sfs_load issue.

If overlayfs, then it's an init issue.
(Because of the limitatioins of overlayfs, the complete stack must be mounted in init.)

**Comment by gyrog** [comment] 2022-10-19 13:08
@dimkr,
I'm saddened to see the removal of overlays processing form init.
In all my playing with overlayfs in my "mio" project, I never got around  to producing a "normal" puppy init with overlayfs support.
The down side to a separate file is the duplication of non-overlayfs specific code.

**Comment by gyrog** [comment] 2022-10-19 13:15
Aa to rewriting init, I've already produced a very large patch to the init script, see my "singly init", which significantly changes the way ".sfs" files are processed, (before 656b135).
One of the things it does is limit the overlayfs processing to only a small number of places.

**Comment by dimkr** [comment] 2022-10-19 13:16
> I'm saddened to see the removal of overlays processing form init.

I'm not removing it, only moving it to a separate file, to make it easier to fix issues while you're writing patches against the "normal" init.

**Comment by gyrog** [comment] 2022-10-19 13:23
Yes, I got that, instead of a single file, we now have 2 files, with significant duplication of code.
It's not worth it.
I would prefer to see an integrated init script.

**Comment by gyrog** [comment] 2022-10-19 13:28
"Singly init" does not generate partial stacks, rather it creates a list of directories in stack order, that are only mounted into an aufs or overlayfs stack after the save layer has been sorted out.
So most of the overlayfs processsing is done in one place, (unfortunately not all.)

**Comment by dimkr** [comment] 2022-10-19 13:33
> with significant duplication of code.

True, but that's just temporary. I want to start with a semi-working baseline equivalent to what we have today, hence the copying to init.overlay. Then, I'll start simplifying and optimizing it.

> I would prefer to see an integrated init script.

I would prefer something I can understand and debug easily. I can't fix issues with overlay support when the init script is a monolithic piece of 1500 lines with a coding style that makes it unreadable (IMO). I'm only human: I'm afraid to touch something I don't understand. I prefer to move the overlay-related stuff to a separate file so I don't risk any "released" Puppy with aufs while I'm working towards the first release-grade Puppy with overlay.

(And sometimes, as the proverb says, "a little copying is better than a little dependency"; copying is OK when the scope of the copied code is known and especially when it's temporary)

**Comment by dimkr** [comment] 2022-10-19 16:43
@mavrothal Build 54 (10.0.54) contains #3515. If I've identified the root cause of the problem inside that pile of spaghetti code correctly, it should be fixed.

**Comment by mavrothal** [comment] 2022-10-19 19:56
Build 54 does load extra sfs fine
Will removal of  the ```[ "$ONE_PART" = "$P_PART" ]``` condition,  affect loading SFSs from other partitions/folders? 
@gyrog , yes we are talking about overlayfs

**Comment by dimkr** [comment] 2022-10-19 20:01
> Will removal of the [ "$ONE_PART" = "$P_PART" ] condition, affect loading SFSs from other partitions/folders?

If I understand the code correctly, and I'm not sure, that `[ "$ONE_PART" = "$P_PART" ]` is an optimization. If it's `P_PART`, it assumes /mnt/pdrv and doesn't check if that's the mount point. The overlay-specific block that loads extra SFSs is the only case where this function is used after the mount point is moved elsewhere, therefore 1) it shouldn't break anything for aufs, which never needed this fix (+ the overhead is minimal) and 2) removing that condition fixes the issue.

**Closed as completed** 2022-10-20 08:11 UTC
