### ISSUE TITLE
Disruption of the /tmp symlink to /initrd/mnt/tmpfs/tmp

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#1327] opened 2019-02-14 01:44 UTC
Re: /tmp symlink to /initrd/mnt/tmpfs/tmp is broken by some pets.

Running Dpup Stretch 7.5 in Pupmode 5 and Pupmode 12, built with recent Woof-CE.

Some pets may use the /tmp directory as a temporary repository from which selected files are moved by the pinstall script to the final destination.

For example, when the PupApps pet (below) is installed the rc files are temporarily added to /tmp/PAPP-install and the pinstall script will only move them to the final destination if they do not already exist from a prior installation.

In this scenario, the pet installs correctly but the /tmp symlink to /initrd/mnt/tmpfs/tmp is broken. This immediately breaks drive icons (pup_event) and other desktop functions.

http://www.smokey01.com/radky/PupApps-3.0.pet

Thanks

**Comment by wdlkmpx** [comment] 2019-02-14 04:57
The only way to fix this is making /tmp a tmpfs again (not a symlink)

Some people might also want /tmp to be a simple directory (in full installs/savefolder) for some apps that require too much space in /tmp .. or for debugging purposes .. maybe through pfix=tmpdir

**Comment by gyrog** [comment] 2019-02-14 08:07
The issue is caused by the existence of a real directory /tmp inside the pet.
The pet can avoid the issue by simply relocating /tmp/PAPP-install to somewhere else,
e.g. /usr/local/PupApps/PAPP-install. And of course appropriately modifying the pinstall.sh.

Note1: in a frugal install /tmp is new for each boot, nothing survives in /tmp from one session to the next.

Note2: /tmp would be better as zram rather than tmpfs, but that requires "init" be able to create a filesystem in the zram.
The init I am currently using, uses zram. I expect to "publish" this soon.

**Comment by gyrog** [comment] 2019-02-14 08:19
Another thought i will play with.
Mount a zram as  /pup_new/tmp and use a directory in that as the top layer in pupmode=5.

**Comment by radky2** [comment] 2019-02-15 02:50
@gyrog and wdlkmpx,

I will update PupApps and other pets to use a directory other than the symlinked /tmp directory for transfer of  files.

Thanks for your quick responses.

**Comment by wdlkmpx** [comment] 2019-06-14 03:58
Talking about zram, i think it's a compressed fs or something. 

Currently /tmp is a symlink to a sub directory in a tmpfs created by init, located in /initrd/mnt/tmpfs/tmp .. this was obviously designed to optimize performance. That's good.

Now a major a cleanup has been merged to testing:
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/initrd-progs/0initrd
History:
https://github.com/puppylinux-woof-CE/woof-CE/commits/testing/initrd-progs/0initrd

Now talking about /tmp, maybe init should not touch it. By default it should be a symlink to the initrd tmpfs.. 

A new boot param could be created, tmp=... and this boot param should be processed by rc.sysinit.

* tmp=symlink (default, symlink to /initrd/mnt/tmpfs/tmp
* tmp=zram
* tmp=dir (tmp is part of the top layer (pupsave/full install).. for debugging purposes..)

...

**Comment by wdlkmpx** [comment] 2019-07-13 19:01
No package should contain files in /tmp or even the /tmp directory (or symlink). So the app must be fixed, closing..

**Closed** 2019-07-13 19:01 UTC

**Comment by s243a** [comment] 2019-07-13 19:23
Relying on what someone should do doesn't sound like a robust strategy to me.
