### ISSUE TITLE
Booting off optical media is broken for saving sessions - all types

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1993] opened 2021-01-04 11:03 UTC
@gyrog - yes I know optical media is dying but it's not dead yet. I can confirm that saving back to optical media is broken in latest slacko 7 and also saving to hard drive or usb. There are no options when shutting down.

Can you take a look please?

**Comment by CollaboratorGCM** [comment] 2021-01-04 21:02
I confirm that ALL of my desktops and laptops boot from their optical
media. But Slacko64 shows problems with the sessions save back to media as
well as having keyboard problems (US/CA) after firstrun.

**Comment by CollaboratorGCM** [comment] 2021-01-04 21:05
And sound discovery when HDMI TV is monitor. This really should be the
default sound in today's world without user intervention.
Or, it should be a firstrun option.

**Comment by gyrog** [comment] 2021-03-06 11:37
@01micko, I haven't noticed this till now.

You do realise that if folk want to boot from CD but save to HD, they can do it the other way around,
i.e. Install Puppy to HD (or USB device) and boot that Puppy from a CD; "FrugalPup->BootCD".
or for something that might have a longer life, install a vfat boot partition "FrugalPup->Boot" and then create a CD that will boot the grub2 on the vfat boot partition using a little script called "bootgrubcd", (although I'm not sure I've published "bootgrubcd").

If pupmode=77 is failing, is it failing in the actual writing to the device, or is it not being setup in 'shutdownconfig'.

And if I were to waste my time on optical media stuff, which ".iso" would I use for testing "eslacko64"?? .

**Comment by CollaboratorGCM** [comment] 2021-03-06 13:06
Thanks for this effort. I thought it was a PC hardware problem: I had burn the DVD on one machine and was attempting to use the DVD on a different PC for boot and session saves. Boots fine; but session save issues.

Now I know the problem is not the PC's DVD hardware as I had suspected.

**Comment by CollaboratorGCM** [comment] 2021-03-06 13:09
BTW: This is **not a priority** for me as I merely save folder instead to HDD on this PC.

**Comment by 01micko** [comment] 2021-03-06 19:15
> You do realise that if folk want to boot from CD but save to HD, they can do it the other way around,
> i.e. Install Puppy to HD (or USB device) and boot that Puppy from a CD; "FrugalPup->BootCD".
> or for something that might have a longer life, install a vfat boot partition "FrugalPup->Boot" and then create a CD that will boot the grub2 on the vfat boot partition using a little script called "bootgrubcd", (although I'm not sure I've published "bootgrubcd").
> 

Yes but probably isn't obvious to the casual user.. I'll think about that.

> If pupmode=77 is failing, is it failing in the actual writing to the device, or is it not being setup in 'shutdownconfig'.
> 
> And if I were to waste my time on optical media stuff, which ".iso" would I use for testing "eslacko64"?? .

In `shutdownconfig`. Slacko64-7.0 has all the facilities.

**Comment by gyrog** [comment] 2021-03-07 06:25
Exactly what fails, and when?

Is pupmode=77 failing?
If so, is it failing to do save on shutdown , or failing to load folders on boot?
Or is it failing to be setup by 'shutdownconfig'

**Comment by 01micko** [comment] 2021-03-07 06:31
It fails to be offered to save back to cd so there is an issue with shutdownconfig. I think that we probably need to check if we booted off a physical optical drive or a 'soft' iso. I haven't looked at the code yet, just guessing.

**Comment by gyrog** [comment] 2021-03-07 06:42
@01micko, that's a start, I'll have a look at the 'shutdownconfig' code.

**Comment by gyrog** [comment] 2021-03-07 09:44
@01micko,
Sorry, my mistake, there is a bug in my recent changes to 'shutdownconfig'.
It stops optical drive dialogs, and also partition selection dialogs from being shown.

I have provided a 'ydrv_slacko_7.0.sfs' in the forum.

I tested by adding this 'ydrv_slacko_7.0.sfs' to the 'slacko-7.0.iso' and burning a CD.
On first shutdown, I got the optical drive dialog.

I could patch 'shutdownconfig' in woof-ce 'testing' branch.
The same bug is also present in 'init-experiment' branch.

**Comment by 01micko** [comment] 2021-03-07 09:50
No worries. `init-experiment` is probably A THOUSAND commits behind by now :laughing: so go direct to `testing`. There are no imminent stable releases so we'll get time to sort it.

I'm uploading a slacko64 8 triple alpha soon from `testing` (slackware - current based - 'soon' to be 15.0. NB: soon is 'relative speak' for Pat Volkerding). The ydrv may well work in that too.

**Comment by gyrog** [comment] 2021-03-07 10:14
woof-ce 'testing' now updated.
So 'shutdownconfig' on 'testing' should be identical to 'shutdownconfig' in the ydrv.

**Comment by 01micko** [comment] 2021-03-07 10:26
Thanks @gyrog - no need for ydrv now :-)

**Comment by gyrog** [comment] 2021-03-07 10:31
No worries.

**Comment by dimkr** [comment] 2021-03-22 09:45
Is this still happening in testing? I can't save when booting dpup from an ISO.

**Comment by gyrog** [comment] 2021-03-22 11:46
@dimkr, I assume that this dpup was woofed in the last few days?

Any chance I can download this version of dpup?

What dialogs did 'shutdownconfig' display?

**Comment by dimkr** [comment] 2021-03-22 14:22
@gyrog Yes, and yes - https://github.com/dimkr/woof-CE/releases/tag/dpupbullseye64-9.0.0-menubar (will be deleted soon, I delete test builds when I don't need them)

**Comment by gyrog** [comment] 2021-03-23 06:32
@dimkr, got it.

I think there may be 2 issues here;

1  The "searching" code that is in the 'init' script may not be being executed.
It should work, provided you are "conservative" in 'shutdownconfig'.
I'll look at this now, just to make sure.

2  'shutdownconfig' should be able to write a SAVESPEC-1234567890 file to an "open" DVD.
This provides a solution no matter what you choose in 'shutdownconfig'.
This is one of those, "I really should get around  to it" kind of things.

Note: The bug I fixed, is in 'shutdownconfig', where it was not showing some dialogs.
That is still fixed in your dpupbullseye64.

**Comment by gyrog** [comment] 2021-03-23 16:27
Yes, the "searching" code in 'init' is being skipped.
I now have 2 patches, to 'init' and 'shutdownconfig'

The patch for 'init' fixes the "no searching" issue, but the "searching" code finds only saves in the root of partitions.
Hence the patch to 'shutdownconfig' so that it doesn't offer "CHANGE FOLDER" if PMEDIA=cd.
I want to do more testing before I commit these patches to woof-ce testing,
so I'll probably commit them to 'init-experiment' soon.

Of course the real solution is to extend the use of a SAVESPEC file to inform 'init' of the choices made in 'shutdownconfig', although that will work only for "open" optical mediia, ones suitable for multi-session.
That requires a significant effort.

Of course a work around for now is to create a "SAVESPEC" file and add that to the optical media,
even if that involves "editing" the iso, before first-boot. That works now with the currrent woof-ce testing, without any patches.

My idea of a starting point would be a stand-alone utility that can produce a SAVESPEC file, and write it to an "open" optical media.

And of course folk can go the other way, do a frugal install of Puppy to a HD type device, and then create a CD/DVD that can boot it, (e.g. FrugalPup->BootCD).

**Comment by gyrog** [comment] 2021-03-23 16:33
FYI,
I've uploaded patch files, 'init-cd-save.diff' and 'shutdownconfig-cd.diff' to [http://www.mediafire.com/folder/ufo1lerdg73j0/savespec](http://www.mediafire.com/folder/ufo1lerdg73j0/savespec)

**Comment by CollaboratorGCM** [comment] 2021-03-24 01:33
Couple quick questions:

1. I am sure that what is meant by the comment "open" DVD we mean a Multisession DVD....Correct?

2. And, since 2020, PUPs have an additional boot option that does NOT require Frugal to get Frugal use including its session saving, the changes will continue to allow SG2D to continue the ISO boot benefit afforded the 2020-2021 PUPs...Correct?

Thanks for the continued great work and attention to the improvements.

**Comment by gyrog** [comment] 2021-03-24 14:35
Yes, "open" DVD we mean a Multisession DVD.

What is the PMEDIA value in your '/etc/rc.d/PUPSTATE'?
That might provide you with a clue as to what situations are effected by these patches.

**Comment by CollaboratorGCM** [comment] 2021-03-24 22:43
I will have to find my DVDs for FossaPUP and FATDOG. But, I think each of those pre-date the current generations of PUP-DOG boot processing. And, I have not only native PUP-DOG DVDs, I also have SG2D DVDs which find the /BOOTISOS on the HDDs/USBs attached to the PC when the DVD presents them for boot selection.

In essence, each approach, native or via SG2D yielded the same exact results for booting the PUP-DOGs to desktop. And, the session save processing was what was expected from the DVD boot use results.

Seems, I may need to restart those testing scenarios when you complete your changes and they show up in the distro releases for tests **or** for GA.

Currently, I am running alpha Slacko64 from SG2D USB boots and have not noticed any sesssion issues, thus far. I save to /Sessions on the local HDDs and reference at boot time the folder via psave option for all testing done.

Oh, one other change I have been using for past month/2 is even on prisine boots, I interrupt at the menu and add a psave option path to the Linux disk on the PC. So at this point of my use, the sessions are asked at shutdown and then saved to that folder upon shutdown if I say yes.

When the next woofCE distro for test or GA is released, I will test the various boot paths mention and detail them for review.

**Comment by gyrog** [comment] 2021-03-25 11:03
"What is the PMEDIA value in your '/etc/rc.d/PUPSTATE'?" is not supposed to be a difficult question.
Just view the file '/etc/rc.d/PUPSTATE' on you running Puppy with at text editor, or "cat" it in a console.
If you look at line 7 of this text file, I believe it will read "PMEDIA='atahd'".
My latest patches refer to the situation when "PMEDIA='cd'", so they won't make a difference.

**Comment by CollaboratorGCM** [comment] 2021-03-25 14:18
Yes, correct.

My current running system booted 12days ago via SG2D USB selecting Slacko64-v8.0alpha for test says "PMEDIA='atahd'"

On another PC, v8.1 booted the same yesterday for test says the same, "PMEDIA='atahd'"

Have not booted Slacko V8s for multisession DVD test at this point. Will do so sometime today.

**Comment by gyrog** [comment] 2021-03-25 18:27
The 'testing' branch should now have a 'shutdownconfig' that doesn't promise anything that 'init' can't deliver.

**Comment by dimkr** [comment] 2021-03-25 18:59
I can confirm https://github.com/dimkr/woof-CE/releases/tag/dpupbullseye64-9.0.0-nojunk is able to save to a hard drive partition when booting from CD.

**Comment by 01micko** [comment] 2021-04-05 12:55
> I can confirm https://github.com/dimkr/woof-CE/releases/tag/dpupbullseye64-9.0.0-nojunk is able to save to a hard drive partition when booting from CD.

Same with slacko64 built today. It can also save back to CD/DVD - tested with physical media.

_However_

The current state of play is this (built from `init-experiment` branch):
- making a USB install with frugalpup-28 with f2stickpup _fails_ at boot - long wait for the partition - seems to time out and I get error messages - I'll take a photo tomorrow because I can't save a log because no keyboard - tested on 2 machines.
- using SuperGrub2 (SG2) - if the iso is on the USB stick it fails to boot - similar timeout to the above point but no error messages, just get dumped to a dead prompt (no keyboard)
- using SG2 - if the iso resides in the BOOTISOS dir on a HD partition it's found by SG2, boots and saves, reboots with save loaded just fine 
 
this is very latest build from `init-experiment`

It appears to me that something may have gone wrong with `wait_for_blkid()` (no, too late for me to look at code - more tomorrow)

there is a slacko64 iso you can test https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/718962296 but not built from `init-experiment`

**Comment by dimkr** [comment] 2021-04-05 19:26
> Same with slacko64 built today. It can also save back to CD/DVD - tested with physical media.

Sounds like a good excuse to release 7.1 😄

**Comment by 01micko** [comment] 2021-04-05 20:13
But need the `wait_for_blkid()` bug fixed

**Comment by CollaboratorGCM** [comment] 2021-04-05 20:53
Confirmed

**Comment by gyrog** [comment] 2021-04-06 08:48
@01micko,
"making a USB install with frugalpup-28 with f2stickpup fails at boot - long wait for the partition - seems to time out and I get error messages - I'll take a photo tomorrow because I can't save a log because no keyboard - tested on 2 machines"

The "wait" is timing out, it would seem that that whatever "blkid" uses as it's source is not being updated.
For me this only happens if I use your kernel, using a different kernel, no-problem.

**Comment by dimkr** [comment] 2021-04-06 08:52
> For me this only happens if I use your kernel, using a different kernel, no-problem.

What kernel reproduces the issue?

**Comment by gyrog** [comment] 2021-04-06 08:53
I was trying to test slacko-alpha-alpha64..... on a usb device.
The "wait-for-partition" timed-out, resulting in predictable error mesages.
I replaced the kernel with a different 64 bit kernel, no-problem.

The thing that's supposed to change is the output from "blkid", when the kernel becomes aware of the partition.

**Comment by gyrog** [comment] 2021-04-06 08:58
Dead keyboard usually means it needs kernel modules, which 'initmodules' can't fix until second boot.

**Comment by gyrog** [comment] 2021-04-06 11:42
I just noticed there is an error in the  'wait_for_blkid' code in 'init', but it is not the current "bug",
there is an "exit 1" when there should be a "return" statement. But this "error" is never activated becuse the rest of the code always calls the function with 2 parameters.

So, I'm producing a patch for the 'wait_for_blkid' code.
I also notied that the way it is called is not very straight forward, so my patch will focus on simpifying that.
I'll be committing it to 'init-experiment' soon.
But, I expect that this patch will have no bearing on the current "bug".
However since I'm working in the area I can easily produce a test 'init' with extra debug tracing if that would be helpful to others.

**Comment by 01micko** [comment] 2021-04-06 12:10
> Dead keyboard usually means it needs kernel modules, which 'initmodules' can't fix until second boot.

Might be the key to the "bug" in linux 5.10 .. building and testing now..

my `slacko64initmodules.txt`
```
xhci_pci,xhci_pci_renesas
```

That's why the keyboard failed and I'm thinking USB in general. Funnily enough, I booted on an sdcard on my laptop just fine.

Oh, and I promised a screenshot..


![PXL_20210406_112501588](https://user-images.githubusercontent.com/1019119/113708728-1cc5fa00-96d1-11eb-86e8-fa3fb6bb85c6.jpg)

**Comment by 01micko** [comment] 2021-04-06 12:33
Yes!

```
CONFIG_USB_XHCI_PCI=y
CONFIG_USB_XHCI_PCI_RENESAS=y

```

they were `=m` so that "bug" is solved. I can probably close this issue but I'll just do a test from booting the iso off USB drive. Back soon.

**Comment by gyrog** [comment] 2021-04-06 12:44
Sorry, that's the problem with your dead keyboard, but I'll be surprised it if fixes the "Waiting for partition" failing.

**Comment by 01micko** [comment] 2021-04-06 12:50
Absolutely **did** fix it... I'm committing the new kernel config momentarily and will be updating all 'in use' branches including `init-experiment`.

Just had success booting of iso on a USB stick and that _was_ broken, but not because of recent commits but because of the kernel config.

**Comment by gyrog** [comment] 2021-04-06 12:52
Yes, of course,  "blkid" can't find a usb device if the kernel has no usb support.

**Closed as completed** 2021-04-06 12:52 UTC

**Comment by 01micko** [comment] 2021-04-06 13:00
Just as a side note, my keyboard has _never_ not been detected in all previous kernels I've used in the last 18 months since I bought it. That was the "clue" to me.

**Comment by peabee** [comment] 2021-04-06 14:18
Just interested what
CONFIG_USB_XHCI_PCI_RENESAS=y  "Support for additional Renesas xHCI controller with firmware"
does as I didn't have that in my configs.....is this common hardware?

**Comment by dimkr** [comment] 2021-04-06 16:37
Puppies with 5.10.x built after https://github.com/puppylinux-woof-CE/woof-CE/runs/2280183894 is done should have the fix.

**Comment by CollaboratorGCM** [comment] 2021-04-06 19:14
I have 7 different BIOS/UEFI PCs to test v8.1.4+ for this problem. Mick, where
can I source your test version?

**Comment by gyrog** [comment] 2021-04-06 20:29
My patch to 'init' is now rather non-urgent.
I'll commit it to 'testing' in a few days.

**Comment by 01micko** [comment] 2021-04-07 04:04
> Just interested what
> CONFIG_USB_XHCI_PCI_RENESAS=y "Support for additional Renesas xHCI controller with firmware"
> does as I didn't have that in my configs.....is this common hardware?

It's an xhci controller. My mobo has it. If absent from any recent  kernel my machine wont have usb access. Need to be builtin for at least my machine to boot from USB.
